Ensure thread and comment authors are always up-to-date
hicommonwealth/commonwealth pull request #1012
Opened 2020-12-16 00:33 UTC by gdjohnson

Closes #1010.

## Description

Previously, posts could originate from the incorrect address on account of a stale `author` value in various comment and thread creation fns. This branch ensures that the user.activeAccount is updated _on function call_, rather than being left over from the component's last redraw.

## Have proper tags been added (for bug, enhancement, breaking change)?
- [x] yes

## Does this PR affect any server routes?
- [ ] yes, and they are tested: [enter the % coverage here]
- [ ] yes, and they are not tested: [enter the % coverage here]
- [ ] yes, but I did not run tests
- [x] no

2020-12-17 20:48 UTC, raykyri reviewed
This seems like a broader problem, we use the `const account = app.user.activeAccount` idiom in many places.

A better answer might be to assign a `key` parameter at the parent DOM node that the whole app is within, with the address and chain of the active account. Then once the key changes, the DOM diffing engine will know to reset the state of the whole page.

2020-12-18 21:46 UTC, raykyri requested changes
As above

2020-12-18 23:05 UTC, gdjohnson commented
@raykyri That makes sense to me! I'll get on it

2020-12-21 18:15 UTC, gdjohnson commented
@raykyri Any evolving feelings, after the weekend, re: the key strategy? I've started reading up on the Mithril docs for more info, but you may have a headstart on me.

2020-12-22 19:54 UTC, raykyri commented
Basically we should check if putting m.redraw() in the right place fixes our problems. Because all the view code gets execute every time there's a redraw, so if there's a stale value for `const account = app.user...` being cached that's likely because the view wasn't redrawn at the right time.

2020-12-23 23:30 UTC, gdjohnson commented
I'm completely unable to replicate the original issue. There's no lag or redraw problem, on master, in switching address / that new active account propagating to the thread submission functions. Not clear why it disappeared.

2020-12-24 01:56 UTC, raykyri commented
I didn't see anything change on master that would have resolved this. Maybe worth revisiting after the holidays...

2021-01-15 21:32 UTC, closed without merging

2021-01-15 21:32 UTC, raykyri commented
Going to close this now since it hasn't replicated...we can reopen later if necessary.