User-set proposal titles, part 4: Author-setting
hicommonwealth/commonwealth pull request #1125
Opened 2021-03-22 16:31 UTC by gdjohnson

[Link to Notion spec.](https://www.notion.so/hicommonwealth/Chain-Entity-Authors-Titles-13-2a0389729cb544c79ab44258b4fd30f8)

Closes #840.

## Description

This branch extends proposal title-setting functionality from admins/mods to proposal authors. The db and models have already been configured in previous pulls to allow storage of author and title data; this ensures that entity archival includes author information, and that the title-setting UI/title-setting endpoint allow authors to update titles.

## How has this been tested?

I've tested setting/fetching on both active and completed treasury and democracy proposals, with several different author/addr combos.

Wasn't quite sure how/if to proceed on unit tests, since it falls in a weird in-between of events/api + have a pretty full plate of projects... If this is something that is high-priority I'll start exploring a best approach.

## Have proper tags been added (for bug, enhancement, breaking change)?
- [x] yes

## Does this PR affect any server routes?
- [ ] yes, and they are tested: [enter the % coverage here]
- [x] yes, and they are not tested: [enter the % coverage here]
- [ ] yes, but I did not run tests
- [ ] no

2021-03-22 21:07 UTC, raykyri commented on client/scripts/views/pages/view_proposal/index.ts
> +    const authorChain = (proposal instanceof OffchainThread) ? proposal.authorChain : app.activeId();
we should just add `chain` to Proposal object in the future, but this seems fine for now

2021-03-22 21:07 UTC, raykyri commented on server/routes/updateChainEntityTitle.ts
> +  if (!userOwnedAddresses.includes(entity.author)) {
This should check that (address matches && chain matches).

2021-03-22 21:09 UTC, raykyri commented on server/routes/updateChainEntityTitle.ts
> +    });
Entities can't have communities.

2021-03-22 21:10 UTC, raykyri requested changes
Minor changes requested.

2021-03-23 01:09 UTC, gdjohnson commented
Requested fixes pushed 👍

2021-03-23 01:28 UTC, merged