[WIP] Wallet Connect Integration
hicommonwealth/commonwealth pull request #1153
Opened 2021-04-28 17:23 UTC by jnaviask

## Description
* Adds models for WebWallet and SignerApi (contracts).
* Adds a global web wallet controller onto app and removes hard association between chain and wallet.
* TODO: refactor/cleanup link_new_address_modal AccountItems to use webWallet methods.
* TODO: clean up NearWallet to use the controller rather than hardcoded logic.
* TODO: remove webWallet from chain entirely (??).
* TODO: ensure metamask account switching (listener event) still works.
* TODO: add wallet connect as alternative Ethereum chain.

## How has this been tested?
TBD

## Have proper tags been added (for bug, enhancement, breaking change)?
- [x] yes

## Does this PR affect any server routes?
- [x] no

2021-05-03 19:31 UTC, raykyri requested changes
Added a few comments about what seemed like stray fetch balance calls for ETH. Although we may want to keep those around (commented out?) as examples for token-gated communities, right now they might introduce problems if there are malfunctioning ETH nodes or EVM nodes.

![image](https://user-images.githubusercontent.com/1273926/116923035-1c634500-ac24-11eb-8677-68f00ab88250.png)

polkadot-js option seems to be missing. Keplr should be capitalized.

![image](https://user-images.githubusercontent.com/1273926/116923126-3b61d700-ac24-11eb-88ad-d8f1541b1ad8.png)

For Marlin, notifyError('Please change your Metamask network') should say which network you should be connected to.

2021-05-03 19:31 UTC, raykyri commented on client/scripts/controllers/app/webWallets/walletconnect_web_wallet.ts
> +      console.log(balance);
why fetch the balance here?

2021-05-03 19:31 UTC, raykyri commented on client/scripts/controllers/app/webWallets/metamask_web_wallet.ts
> +      console.log(balance);
why fetch the balance here?

2021-05-03 19:31 UTC, raykyri commented on client/scripts/controllers/app/webWallets/walletconnect_web_wallet.ts
> +        infuraId: 'b19b8175e688448ead43a0ab5f03438a'
should this be factored out into the constants file?

2021-05-03 19:31 UTC, raykyri commented on client/scripts/controllers/chain/ethereum/chain.ts
> +    const infuraId = 'b19b8175e688448ead43a0ab5f03438a';
should move to constants

2021-05-03 19:31 UTC, raykyri commented
How should I test WalletConnect integration?

2021-05-03 19:35 UTC, jnaviask commented
> How should I test WalletConnect integration?

You can try logging in with it and verify the registration and existing login flows work, maybe also try a transaction to ensure signing works, but unsure what exactly you're looking for.

2021-05-03 21:36 UTC, jnaviask commented
Marlin doesn't say "please change your Metamask network" anymore -- that was removed. (Or, what file is that in?)

2021-05-04 19:28 UTC, raykyri commented
After going to the Web3 address login modal, and canceling it, and pressing Try Again, the Metamask wallet is not initialized. We should replace that Try Again button with the same dropdown menu that is used in the Login component now that we have both Metamask and WalletConnect options for ETH.

2021-05-04 19:28 UTC, raykyri commented
Otherwise looks good!

2021-05-04 20:26 UTC, jnaviask commented
> After going to the Web3 address login modal, and canceling it, and pressing Try Again, the Metamask wallet is not initialized. We should replace that Try Again button with the same dropdown menu that is used in the Login component now that we have both Metamask and WalletConnect options for ETH.

Attempted to fix this -- try it out again and see if it works.

2021-05-06 00:19 UTC, raykyri commented
LGTM 🤘

2021-05-06 00:21 UTC, merged