Jake.snapshot linking
hicommonwealth/commonwealth pull request #1401
Opened 2021-09-10 22:51 UTC by dillchen

2021-09-11 13:50 UTC, jnaviask reviewed
Seems like ... it won't blow up the codebase? But I wouldn't call it ready to go... Main concern is one snapshot link vs many.

2021-09-11 13:50 UTC, jnaviask commented on client/scripts/controllers/server/threads.ts
> +    const thread = modelFromServer(response.result);
I recommend having this new route return an id or link rather than the entire thread object.

2021-09-11 13:50 UTC, jnaviask commented on client/scripts/views/components/stage_editor.ts
> +          app.chain.meta.chain.snapshot && m(SnapshotProposalSelector, {
is `app.chain` always set here?

2021-09-11 13:50 UTC, jnaviask commented on client/scripts/views/components/stage_editor.ts
> +                  await app.threads.setLinkedSnapshotProposal({ threadId: thread.id,
So we're only linking the *last* snapshot proposal in the list? Because we only support linking a single one.

2021-09-11 13:50 UTC, jnaviask commented on client/scripts/views/pages/view_proposal/header.ts
> +    if (!app.chain.meta.chain.snapshot) return;
Should make this `app.chain?.meta...`

2021-09-13 17:25 UTC, dillchen commented
small fixes to look at: adding external link to Snapshot page

2021-09-13 20:47 UTC, dillchen commented on client/scripts/views/components/stage_editor.ts
> +          app.chain.meta.chain.snapshot && m(SnapshotProposalSelector, {
resolved

2021-09-13 20:56 UTC, dillchen commented
@jnaviask, so we'll have to follow up on many <> many Thread to Snapshot Linking. The UI doesn't support this well.

2021-09-13 21:15 UTC, zakhap commented
Still reviewing but: 
1. There's a terrrrrrible bug where if you are in a snapshot proposal, it continuous hit the route `/fetchThreadForSnapshot` (100s of times a minute).

2021-09-13 21:23 UTC, zakhap commented
2. When opening the Stages modal (after clicking "Connect a Proposal"), there are a bunch of redraw error upon selecting a snapshot proposal. See below:

<img width="612" alt="Screen Shot 2021-09-13 at 2 21 57 PM" src="https://user-images.githubusercontent.com/16248081/133158294-03ee50cc-2e79-4c5c-a52f-78d5f71ab82a.png">

2021-09-13 22:42 UTC, zakhap requested changes
Just a few things to fix and a few questions.

2021-09-13 22:42 UTC, zakhap commented on client/scripts/views/pages/view_proposal/header.ts
> +  currentSnapshot
I'm not sure I understand why this naming convention change was necessary? snapshot either exists or is null. seems a bit clunky.

2021-09-13 22:42 UTC, zakhap commented on client/scripts/views/pages/view_proposal/header.ts
> +    ]);
these lines above should all be linted to be more compact.

2021-09-13 22:42 UTC, zakhap commented on server/routes/updateThreadLinkedSnapshotProposal.ts
> +  // }
do we need to keep this for any reason?

2021-09-13 22:42 UTC, zakhap commented on server/routes/updateThreadLinkedSnapshotProposal.ts
> +  // TODO: should we verify proposal exists here?
this seems important

2021-09-13 23:18 UTC, dillchen commented on server/routes/updateThreadLinkedSnapshotProposal.ts
> +  // }
it's a TODO for the future

2021-09-13 23:18 UTC, merged