Convert Create Community Modal to Page
hicommonwealth/commonwealth pull request #1529
Opened 2021-11-15 00:24 UTC by true-eye

![image](https://user-images.githubusercontent.com/46362478/141705130-62739ee8-0e16-42aa-9d33-67e2de285e1a.png)

2021-11-15 18:03 UTC, gdjohnson requested changes
Hey James, nice work. I managed to make a new offchain community and set some toggles. I left some minor comments about some wrapping divs and commented-out code.

We may want some kind of header or wrapping layout page, since right now, besides the "Back" button there's no way for the user to navigate out/away from the page. But that's a more high-level design issue that I'll leave to @zakhap's discretion.

Also, can we get a little more padding above the "Save changes" button?

Last, can we get the "Privacy" and "Invites" toggles to be inline with the text? The table's wide enough it should be possible, perhaps even with a simple `display: flex` on the wrapping `td` ele.

2021-11-15 21:48 UTC, zakhap commented on client/scripts/views/pages/create_community.ts
> +    return m('.class', [
👍 Whenever we return a component, the top-level classname should be representative of the Component name as well.

2021-11-15 21:48 UTC, zakhap commented on client/scripts/views/pages/create_community.ts
> +    // mixpanel.track('New Community', {
Yes, just remove all the mixpanel stuff here

2021-11-18 13:06 UTC, OliveSonDev commented on client/scripts/views/pages/create_community.ts
> +    return m('.class', [
Plz check last commit.

2021-11-18 13:06 UTC, OliveSonDev commented on client/scripts/views/pages/create_community.ts
> +    return m('.class', [
Plz check last commit.

2021-11-18 13:07 UTC, true-eye commented on client/scripts/views/pages/create_community.ts
> +    return m('.class', [
Plz check last commit.

2021-11-18 13:07 UTC, true-eye commented on client/scripts/views/pages/create_community.ts
> +    return m('.class', [
Plz check last commit.

2021-11-18 13:07 UTC, true-eye commented on client/scripts/views/pages/create_community.ts
> +    // mixpanel.track('New Community', {
Plz check last commit.

2021-11-18 18:43 UTC, zakhap requested changes

2021-11-18 18:43 UTC, zakhap commented on client/scripts/views/pages/create_community.ts
> +    return m('div', { class: 'container CreateCommunity' }, [
One last change before merging this PR: 

- We should return this form inside of a Sublayout component like all of the other pages on CW. Linking to a blank page with just a form isn't going to cut it. 
  - Pass the attr `hideSidebar: true;` into Sublayout as this page isn't scoped within a community, so no need for the sidebar. (This should not impact the view of the SidebarSwitcher, just the Sidebar menu)

2021-11-19 02:32 UTC, zakhap commented
After merging in an update to the create community modal, this PR is out of sync with master. You'll need to move over the new code from PR #1534.

2021-11-24 15:28 UTC, jnaviask approved these changes

2021-11-24 15:31 UTC, jnaviask reviewed
This is not ready to go, I'm gonna take over work on it for now in a new branch.

2021-12-01 19:08 UTC, closed without merging