Add custom & infinite poll durations
hicommonwealth/commonwealth pull request #1605
Opened 2021-12-28 18:23 UTC by gdjohnson

![image](https://user-images.githubusercontent.com/22281010/147595454-38a0aa34-b063-42bd-a5ff-109c3cb1d63f.png)

This branch allows thread authors/poll creators to set custom durations between 1-30 days, and to set their polls to never expire (i.e. be "infinite"). 

To test, create a poll, enable polling, and enable custom durations. Use the dropdown menu to try specific day-lengths and "Infinite." Poll copy & expiration should update accordingly. 

In the database, infinite polls should have an offchain_voting_ends_at value of NULL. Previously, we used offchain_vote_ends_at moment objects as a pseudo-boolean for conditionally rendering polls. (1) This is fragile, (2) it no longer works with polls that lack expiration dates. Therefore, I have added an additional offchain_voting_enabled true boolean column to OffchainThreads, with a migration that sets this boolean TRUE for all polls that currently have offchain_voting_ends_at values.

2021-12-28 23:11 UTC, zakhap commented on server/migrations/20211228174821-ensure-old-polls-have-boolean-enabled.js
> +module.exports = {
We should merge these two migrations

2021-12-29 00:29 UTC, zakhap approved these changes
@jnaviask if we're ok with this PR having two migrations instead of one, we can merge + deploy this tomorrow. It works as expected

2021-12-29 00:38 UTC, zakhap requested changes
Actually have to revoke my approval:
- When voting on a poll with "Infinite" set, the vote fails to be accepted. "Error submitting vote. Maybe the poll has already ended?"

2021-12-29 21:01 UTC, zakhap commented
Also weird UI glitch on the dropdown menu tooltip thing where the arrow is not centered

2021-12-30 17:47 UTC, gdjohnson commented on server/migrations/20211228174821-ensure-old-polls-have-boolean-enabled.js
> +module.exports = {
On it!

2021-12-30 18:51 UTC, gdjohnson commented
@zakhap Should be ready for re-review; migrations have been merged, popover arrow display fixed, and infinite voting issues patched.

I've also added code to ensure (1) newly added polls live-update on threads; (2) that users cannot submit a new poll without a (required on the backend) name + set of voting choices.

2021-12-30 21:20 UTC, zakhap approved these changes

2021-12-30 21:20 UTC, merged