New notification settings page
hicommonwealth/commonwealth pull request #2088
Opened 2022-08-29 13:15 UTC by affordances

2022-09-01 20:32 UTC, dillchen commented
As a note, we should always include joined community (and then filter by communities that a user has already joined), to allow users to toggle individual subscriptions. Right now, joining default adds to you to subscriptions, but if u turn off you'll still want to manage this. Right now communities currently disappear (because there will not be any Notification Subscriptions).

2022-09-08 15:01 UTC, zakhap commented on packages/commonwealth/client/scripts/app.ts
> +              'views/pages/notification_settings/index',
i don't believe this is necessary? stylistic sugar question but pushback is fine.

2022-09-08 18:39 UTC, zakhap reviewed
PR seems to work fine for me now! 

Want @gdjohnson to take a review being that you put your eyes on it too

2022-09-12 21:12 UTC, zakhap commented
just found a bug in the notification settings page where it breaks if it has difficulty parsing the name. for example `dydx/discussion/5011-hedgie-holders-x-extra-trading-rewards` if you subscribe to it and then go to the notification settings page, you’ll see it break. i'll try to fix this momentarily.

2022-09-12 21:31 UTC, zakhap commented
<img width="666" alt="Screen Shot 2022-09-12 at 5 29 07 PM" src="https://user-images.githubusercontent.com/16248081/189761977-0dcf2524-80fe-458b-a576-063cd4eca4e6.png">

was able to get the title rendering. but the short description based on body is still broken? 

ALSO, we need the copy to explain the type of subscription. "Comments on X Thread" / "Reactions to Y Comment" etc. The double rows don't make sense without clearer copy.

2022-09-14 19:04 UTC, zakhap requested changes
broken for dill, will get more data on error shortly

2022-09-16 15:17 UTC, zakhap approved these changes
Should be good to go 💪

2022-09-16 15:17 UTC, merged