Sidebar switcher redesign, phase 1
hicommonwealth/commonwealth pull request #2093
Opened 2022-08-30 18:52 UTC by gdjohnson

This branches replaces the sidebar icons / buttons with the new Global Nav Bar design components.

It does not: (1) add new menu components (2) add the current community overlay display.

2022-08-31 21:06 UTC, zakhap approved these changes
I like this, but maybe we wait for part 2 to be ready? Will take a screenshot of in-between state to share with Aden

2022-08-31 21:07 UTC, zakhap commented
<img width="280" alt="Screen Shot 2022-08-31 at 2 07 07 PM" src="https://user-images.githubusercontent.com/16248081/187782295-4124cd26-eb5c-4608-ac36-aaf6ddcd4e20.png">

2022-09-01 14:05 UTC, gdjohnson commented
> I like this, but maybe we wait for part 2 to be ready? Will take a screenshot of in-between state to share with Aden

Yeah that's fine, doing this project in piecemeal branches has been annoying anyway, I'll just lump things together

2022-09-08 19:11 UTC, zakhap requested changes
1. If full screen on mobile, clicking a topic changes the underlying filter but _doesn't close the sidebar_

2022-09-08 20:06 UTC, affordances requested changes

2022-09-08 20:06 UTC, affordances commented on packages/commonwealth/client/styles/components/sidebar/index.scss
>      font-size: 18px;
Are you replacing these with `CWText` in a later phase?

2022-09-08 20:06 UTC, affordances commented on packages/commonwealth/client/styles/components/sidebar/index.scss
>        margin-bottom: 15px;
Should be on 8px grid.

2022-09-08 20:06 UTC, affordances commented on packages/commonwealth/client/styles/components/sidebar/sidebar_quick_switcher.scss
> +    padding: calc(#{$sidebar-community-header-height} + 4px) 4px 4px;
Why do it this way instead of just having the presence of `CommunityHeader` push the others down?

2022-09-08 20:06 UTC, affordances commented on packages/commonwealth/client/styles/components/sidebar/sidebar_section.scss
> +    @include small {
Spaces between styles and mixins.

2022-09-08 20:06 UTC, affordances commented on packages/commonwealth/client/styles/sublayout.scss
> +      @include smallInclusive {
Spaces between styles and mixins.

2022-09-08 20:06 UTC, affordances commented on packages/commonwealth/client/styles/sublayout.scss
> +          display: flex !important;
Why `!important`?

2022-09-08 20:06 UTC, affordances commented on packages/commonwealth/client/styles/sublayout_header_left.scss
> +    @include mediumSmallInclusive {
Space here.

2022-09-08 20:06 UTC, affordances commented on packages/commonwealth/client/styles/sublayout_header_left.scss
> +    @include mediumSmallInclusive {
Space here.

2022-09-08 20:06 UTC, affordances commented on packages/commonwealth/client/styles/sublayout_header_left.scss
> +    cursor: pointer;
If you make it a `CWIconButton` as suggested above, you won't need `cursor: pointer`.

2022-09-08 20:06 UTC, affordances commented on packages/commonwealth/client/styles/sublayout_header_left.scss
> +  .Icon.sidebarCollapse,
Might make more sense to just enclose the icon button in a div and style that.

2022-09-08 20:08 UTC, affordances commented
Forgot to mention: please delete all of your unused imports.

2022-09-08 20:13 UTC, affordances commented
Are these supposed to be different colors?

<img width="285" alt="Screen Shot 2022-09-08 at 9 13 18 PM" src="https://user-images.githubusercontent.com/13058678/189216898-6341ed56-dafd-4a25-89f3-98e872dbfd4c.png">

2022-09-12 21:41 UTC, zakhap commented
I'll resolve the rest of these comments tomorrow

2022-09-15 14:59 UTC, zakhap approved these changes
After careful QA, seems to be great!

2022-09-15 15:01 UTC, affordances approved these changes

2022-09-15 15:12 UTC, merged

2022-09-16 15:54 UTC, gdjohnson commented on packages/commonwealth/client/scripts/views/sublayout.tsx
> +            <SublayoutHeaderLeft parentState={this} />
Yes