Permissions pr3 Part 1
hicommonwealth/commonwealth pull request #2227
Opened 2022-11-01 22:05 UTC by dantrinh

## Description

1.Updated BASE_PERMISSIONS in roles.ts
2.Added chain permissions columns with new migration
3. Added community role permissions into isAddressPermitted

## Motivation and Context

## How has this been tested?

## Does this PR affect any server routes?
- [ ] yes
- [ ] no

## If this PR affects server routes, what are the security implications?

## Have proper tags been added (for bug, enhancement, breaking change)?
- [ ] yes

2022-11-01 22:16 UTC, dantrinh commented
@jnaviask Good to check!

2022-11-11 14:13 UTC, jnaviask requested changes
One small change -- otherwise this is good.

2022-11-11 14:13 UTC, jnaviask commented on packages/commonwealth/server/util/roles.ts
> +  // add chain default permissions to beginning of permissions array
We should try to construct the permissions array more cleanly here, because later on we'll add several more layers of this hierarchy (topics, etc).

2022-11-11 14:16 UTC, jnaviask approved these changes
Actually this is fine for now.

2022-11-11 14:16 UTC, merged