Conversions 5
hicommonwealth/commonwealth pull request #2770
Opened 2023-02-10 22:41 UTC by affordances

2023-02-14 22:01 UTC, jnaviask commented
Landing page is not fully working (community search field doesn't work, other UI elements are weird) -- is that expected?

2023-02-14 22:56 UTC, zakhap requested changes
<img width="1159" alt="Screen Shot 2023-02-14 at 5 55 40 PM" src="https://user-images.githubusercontent.com/16248081/218881789-4cdf1875-fad4-4195-bd87-0e9f9a667adf.png">

Somehow threads are no longer working again? Jake fixed this earlier today. We need this resolved before merging.

2023-02-14 23:02 UTC, zakhap approved these changes
Actually Jake's PR wasn't yet merged my bad. looks ok to me

2023-02-15 03:26 UTC, jnaviask approved these changes

2023-02-15 03:26 UTC, merged