Misc errors
hicommonwealth/commonwealth pull request #2807
Opened 2023-02-15 19:29 UTC by affordances

2023-02-15 22:24 UTC, zakhap requested changes
just 2 comments!

2023-02-15 22:24 UTC, zakhap commented on packages/commonwealth/client/scripts/views/pages/notifications/index.tsx
> +  );
we should sort these by time so they're interspersed.

2023-02-15 22:24 UTC, zakhap commented on packages/commonwealth/client/scripts/views/components/countdown.tsx
> +  return <Countdown duration={blocknumToDuration(block)} />;
Time seems to be inverted here?

<img width="854" alt="Screen Shot 2023-02-15 at 5 20 14 PM" src="https://user-images.githubusercontent.com/16248081/219197319-a890fa56-7f56-4f38-9ad7-949e9afe3748.png">
<img width="441" alt="Screen Shot 2023-02-15 at 5 20 45 PM" src="https://user-images.githubusercontent.com/16248081/219197326-2e780c7c-45bc-4d02-be9c-249ce6a9821a.png">

2023-02-16 17:41 UTC, jnaviask approved these changes

2023-02-16 17:41 UTC, merged