Added message to user in case of client or server error
hicommonwealth/commonwealth pull request #2960
Opened 2023-02-28 15:33 UTC by martins87

## Description

An environment variable (SLACK_FEEDBACK_WEBHOOK) was missing locally, so the response message below was being shown after the user clicked on "Send feedback" button 
`{"error":"The \"urlObject\" argument must be one of type object or string. Received undefined"}`

A more clear message now appears in case of an error.

## Motivation and Context

## How has this been tested?

## Does this PR affect any server routes?
NO

## If this PR affects server routes, what are the security implications?

## Have you added the issue number here?
(In the right sidebar, under "development")

2023-02-28 21:58 UTC, jnaviask commented
Could we have an error or a log message on the server-side route that catches when you don't have the environment variable set?

2023-03-01 03:30 UTC, martins87 commented
> 

@jnaviask did it, please check.

2023-03-02 16:56 UTC, jnaviask requested changes
- Please add a log.error line to the server saying "No slack webhook found" or something like that.
- Please make error 500 because it's a server error and not a user error.

2023-03-02 17:47 UTC, martins87 commented
> * Please add a log.error line to the server saying "No slack webhook found" or something like that.
> * Please make error 500 (`ServerError`) because it's a server error and not a user error.

@jnaviask changes made

2023-03-06 23:27 UTC, CowMuon approved these changes

2023-03-06 23:29 UTC, merged