Conversions 9
hicommonwealth/commonwealth pull request #2961
Opened 2023-02-28 15:48 UTC by affordances

2023-03-02 16:40 UTC, jnaviask requested changes
- Poll editor modal does not render.
- Finish Axie Login works.
- Didn't notice any changes to search bar (still broken)
- Collapsible body text: show more works, but can't find show less, is that gone now?

2023-03-02 16:51 UTC, jnaviask commented
Also -- this doesn't have a ticket attached -- turns out some of this work overlaps with #2970. We need to avoid duplicating work in the future.

2023-03-02 17:08 UTC, affordances commented on packages/commonwealth/client/scripts/views/modals/poll_editor_modal.tsx
> +    setOptions(['', '']);
I don't understand what you're proposing here.

2023-03-02 17:14 UTC, affordances commented
> Also -- this doesn't have a ticket attached -- turns out some of this work overlaps with #2970 (poll editor). We need to avoid duplicating work in the future. This is where tickets should be helpful.

If you merge https://github.com/hicommonwealth/commonwealth/pull/2970, I can pull `react` into this branch and the duplicated work (which took like two minutes) will go away. That's why I asked for https://github.com/hicommonwealth/commonwealth/pull/2970 to be merged ASAP.

2023-03-06 23:02 UTC, CowMuon commented
> If you merge https://github.com/hicommonwealth/commonwealth/pull/2970

#2970 was merged, where are we with this story? It's starting to look a bit stale.

2023-03-06 23:22 UTC, zakhap commented
> > If you merge #2970
> 
> #2970 was merged, where are we with this story? It's starting to look a bit stale.

We just haven't gotten around to testing it again. Time to do that tonight! 🚀

2023-03-07 16:20 UTC, merged