Dashboard bell icon - update on click
hicommonwealth/commonwealth pull request #3133
Opened 2023-03-14 22:52 UTC by mhagel

## Link to Issue
Closes: #3114 

## Description of Changes
- trigger local state update after subscribe call
- Bell icon reflects current notification subscription click action

## Test Plan
- Unit tested the `FIXME()` call.
- CA (click around) tested on local and frack:
  - http://localhost:8080/dashboard/for-you : click bell to subscribe / unsubscribe
  - expect icon to update

## Other Considerations

-

2023-03-14 22:56 UTC, mhagel commented on packages/commonwealth/client/scripts/views/pages/user_dashboard/user_dashboard_row_bottom.tsx
> +  };
I was tempted to turn `helpers.ts` into a custom hook so this state update could be included there, but that is a bit of a heavy pattern update. I will suggest this in future PRs, but I'll keep the diff light for now.

2023-03-14 23:00 UTC, mhagel commented on packages/commonwealth/client/scripts/views/pages/user_dashboard/user_dashboard_row_bottom.tsx
> +  const [update, setUpdate] = useState<boolean>(false);
All we need is a local state update to get the latest from `app` state, so this is just a binary toggle that we flip after `subscribeToThread ` is called. 

This probably works elsewhere, so it _might_ be a better pattern for other recent work I did relying on `app` state.

2023-03-15 14:20 UTC, masvelio requested changes
previously we stumble upon the problem like this so we have a hook for that => useForceRerender, please use it

2023-03-15 15:43 UTC, mhagel commented on packages/commonwealth/client/scripts/views/pages/user_dashboard/user_dashboard_row_bottom.tsx
> +  const [update, setUpdate] = useState<boolean>(false);
Done. Thanks!

2023-03-15 16:18 UTC, masvelio approved these changes
good job!

2023-03-15 17:07 UTC, merged