Alex.bet1 react bug fixes
hicommonwealth/commonwealth pull request #3375
Opened 2023-04-07 16:45 UTC by alexyoung23j

## Link to Issue
Closes: #3373 

## Description of Changes
- Fixes the bugs described in the ticket. Gets react bet1 at parity with the original bet 1 branch
- 

## Test Plan
- Tested locally. 
  - 

## Deployment Plan

1. 

## Other Considerations

-

2023-04-10 19:38 UTC, jnaviask commented
Contracts page does not load for me. Maybe depends on #3352 ?

2023-04-10 19:42 UTC, jnaviask requested changes
See comment.

2023-04-11 09:27 UTC, masvelio commented on packages/commonwealth/client/scripts/views/pages/contracts/contract_card.tsx
> +                    onDeleteSuccess={onEditSuccess}
I think onDelete and onEdit should be two different props

2023-04-11 20:27 UTC, jnaviask approved these changes

2023-04-11 20:28 UTC, merged