Fixed infinite thread loop
hicommonwealth/commonwealth pull request #3385
Opened 2023-04-10 18:09 UTC by kurtisassad

## Link to Issue
Closes: #3300

## Description of Changes
- Fix dependency array for useEffect of ViewThread Component

## Test Plan
- CA (click around) tested on local

2023-04-10 19:41 UTC, jnaviask commented
Does not fix. Still getting infinite of these:
```
GET /api/getThreads?chain=dydx&ids%5B%5D=10107 304 5.901 ms - -
GET /api/ce/entities?chain=dydx 304 427.136 ms - -
POST /api/reactionsCounts 200 2.597 ms - 32
GET /api/getThreads?chain=dydx&ids%5B%5D=10107 304 7.429 ms - -
GET /api/ce/entities?chain=dydx 304 421.848 ms - -
POST /api/reactionsCounts 200 2.780 ms - 32
GET /api/getThreads?chain=dydx&ids%5B%5D=10107 304 5.907 ms - -
GET /api/ce/entities?chain=dydx 304 417.894 ms - -
POST /api/reactionsCounts 200 2.952 ms - 32
GET /api/getThreads?chain=dydx&ids%5B%5D=10107 304 5.613 ms - -
GET /api/ce/entities?chain=dydx 304 502.394 ms - -
POST /api/reactionsCounts 200 3.848 ms - 32
GET /api/getThreads?chain=dydx&ids%5B%5D=10107 304 5.733 ms - -
GET /api/ce/entities?chain=dydx 304 491.818 ms - -
POST /api/reactionsCounts 200 3.531 ms - 32
GET /api/getThreads?chain=dydx&ids%5B%5D=10107 304 5.693 ms - -
GET /api/ce/entities?chain=dydx - - ms - -
```

2023-04-10 19:41 UTC, jnaviask requested changes
See comment.

2023-04-11 14:53 UTC, kurtisassad commented
> Does not fix. Still getting infinite of these:
> 
> ```
> GET /api/getThreads?chain=dydx&ids%5B%5D=10107 304 5.901 ms - -
> GET /api/ce/entities?chain=dydx 304 427.136 ms - -
> POST /api/reactionsCounts 200 2.597 ms - 32
> GET /api/getThreads?chain=dydx&ids%5B%5D=10107 304 7.429 ms - -
> GET /api/ce/entities?chain=dydx 304 421.848 ms - -
> POST /api/reactionsCounts 200 2.780 ms - 32
> GET /api/getThreads?chain=dydx&ids%5B%5D=10107 304 5.907 ms - -
> GET /api/ce/entities?chain=dydx 304 417.894 ms - -
> POST /api/reactionsCounts 200 2.952 ms - 32
> GET /api/getThreads?chain=dydx&ids%5B%5D=10107 304 5.613 ms - -
> GET /api/ce/entities?chain=dydx 304 502.394 ms - -
> POST /api/reactionsCounts 200 3.848 ms - 32
> GET /api/getThreads?chain=dydx&ids%5B%5D=10107 304 5.733 ms - -
> GET /api/ce/entities?chain=dydx 304 491.818 ms - -
> POST /api/reactionsCounts 200 3.531 ms - 32
> GET /api/getThreads?chain=dydx&ids%5B%5D=10107 304 5.693 ms - -
> GET /api/ce/entities?chain=dydx - - ms - -
> ```

Thanks, there was also an infinite loop on the discussions page as well which I thought was the only issue.

2023-04-11 15:49 UTC, jnaviask approved these changes

2023-04-11 15:49 UTC, merged