Mark.active inactive prop
hicommonwealth/commonwealth pull request #3564
Opened 2023-04-21 22:54 UTC by mhagel

## Link to Issue
Closes: #3152

## Description of Changes
- Lazy-loads completed Cosmos proposals after chain init
- 

## Test Plan
- CA (click around) tested on local and frack:
  - TODO page
  - 

## Deployment Plan

1. 

## Other Considerations

-

2023-04-24 20:10 UTC, jnaviask commented
@mhagel What's left for this PR? Would love for it to go out in the next few days!

2023-04-24 23:37 UTC, mhagel commented on packages/commonwealth/client/scripts/hooks/cosmos/useGetCompletedCosmosProposals.tsx
This is the hook that lazy-loads completed proposals on the /proposals page

2023-04-24 23:47 UTC, mhagel commented
@jnaviask got tests sorted out. R4R now

I am leaving some v1beta1 tests commented out, to be addressed in #3563 
They work locally for osmosis.

2023-04-24 23:48 UTC, mhagel commented
Sorry for the large diff. Most of this is moving methods and files around. I will highlight important changes.

2023-04-24 23:48 UTC, mhagel commented on packages/commonwealth/client/scripts/views/pages/proposals.tsx
here is the lazy load

2023-04-24 23:49 UTC, mhagel commented on packages/commonwealth/test/integration/api/devnet/cosmos/proposalTx.spec.ts
> +
these work locally, but not in CI. I will convert them to a v1beta1 devnet in the next issue, as noted

2023-04-25 14:59 UTC, jnaviask requested changes
Getting infinite bobber on /proposals page for both osmosis and juno when I navigate via the sidebar after loading the forum. Works fine when I navigate directly to the proposals page.

2023-04-25 17:55 UTC, mhagel commented
>Getting infinite bobber on /proposals page for both osmosis and juno when I navigate via the sidebar after loading the forum. Works fine when I navigate directly to the proposals page.

Was an existing issue. Fixed.
@jnaviask

2023-04-25 18:07 UTC, jnaviask commented
Great -- looks great, however, it's reloading the proposals every time you navigate to the page during a session, rather than simply pulling the data out from the store. We should really not fetch this data more than once per visit.

2023-04-25 19:05 UTC, mhagel commented on packages/commonwealth/client/scripts/hooks/cosmos/useGetCompletedCosmosProposals.tsx
> +
@jnaviask now using the store instead of refetching

2023-04-25 19:06 UTC, mhagel commented on packages/commonwealth/client/scripts/hooks/cosmos/useGetCompletedCosmosProposals.tsx
> +
wait, not ready yet

2023-04-25 19:06 UTC, mhagel reviewed
still need to fix something

2023-04-25 21:36 UTC, mhagel commented on packages/commonwealth/client/scripts/hooks/cosmos/useGetCompletedCosmosProposals.tsx
> +
ready now

2023-04-25 21:36 UTC, mhagel commented on packages/commonwealth/client/scripts/hooks/cosmos/useGetCompletedCosmosProposals.tsx
> +
Fixed duplicate call issue with useRef

2023-04-25 21:37 UTC, mhagel commented
>still need to fix something
all fixed and ready to go!

2023-04-25 22:04 UTC, jnaviask approved these changes

2023-04-25 22:05 UTC, merged