Proposal Linking Backend implementation & tests
hicommonwealth/commonwealth pull request #3575
Opened 2023-04-24 20:44 UTC by ianrowan

## Link to Issue
Closes: #3541 

## Description of Changes
- Database migration to add JSONB links column to Threads + consolidate existing links(snapshot, threads, chainEntityMeta) into new column for existing records
- New routes
    - `POST /linking/getLinks`: get bi-directional links for threads <-> (threads, snapshot, proposals)
    - `POST /linking/addThreadLinks`: add Links to a existing thread_id
    - `DELETE /linking/deleteLinks`: delete links from Thread Id
- API integration tests 

## Test Plan
- Mocked a jwt in postman and tried all configs 
- Built and confirmed all integration tests succeed with full coverage

## Deployment Plan
1. Currently the migration will need to run + frontend update to use the routes on both read/write. This migration does not delete old data to ensure easy rollback. Please confirm if this is the correct approach.

## Other Considerations
- Proposals are stored generically, so FE will need to know how to build a proposal link based on the chain(ie ChainEntities for evm chains, ? for cosmos chains) 
- In the migration, links in the `ChainEntityMeta` table were consolidated as links of type `proposal` with `id: ce_id` please advise if this is how we want to approach this migration

2023-04-25 18:21 UTC, jnaviask requested changes
Generally happy with this aside from a few small comments. Would like to investigate the migration, specifically it needs to be within a sequelize transaction + then I worry about migration performance / whether we may encounter deadlocks.

Overall, though, looks great.

2023-04-25 18:21 UTC, jnaviask commented on packages/commonwealth/server/migrations/20230421205344-add_thread_link.js
> +    await queryInterface.addColumn('Threads', 'links', {
Migration should be transactionalized. Note that this makes the loop here tricky, as we will need to lock the entire table for the duration of the migration. I wonder if there's a cleaner way we can make these updates...

2023-04-25 18:21 UTC, jnaviask commented on packages/commonwealth/server/routes/linking/addThreadLinks.ts
> +  req: Request,
Can we used `TypedRequest[Body|Query]` and `TypedResponse` here / throughout?

2023-04-25 19:51 UTC, jnaviask commented
@ianrowan feel free to take over frack and test out the performance of the migration. Hopefully is under 5s.

Also, are the unit test failures expected?

2023-04-25 20:24 UTC, ianrowan commented
@jnaviask 
<img width="401" alt="image" src="https://user-images.githubusercontent.com/36428666/234395048-43dda74a-4e94-4948-8a20-4cfc67caefcb.png">
Looks like its under 5s 

And as for unit tests - the failure is an un-related file/test related to react

2023-04-25 22:07 UTC, jnaviask requested changes
One more small fix then we can merge this.

2023-04-25 22:07 UTC, jnaviask commented on packages/commonwealth/server/migrations/20230421205344-add_thread_link.js
> +      const [threads, metadata] = await queryInterface.sequelize.query(
We should have these read queries as part of the transaction as well.

2023-04-26 14:23 UTC, jnaviask approved these changes
Will merge to feature then rereview before merge to master

2023-04-26 14:23 UTC, merged