Analytics on God Mode Panel
hicommonwealth/commonwealth pull request #4137
Opened 2023-06-05 20:13 UTC by alexyoung23j

## Link to Issue
Closes: #3865 

## Description of Changes
- Adds requested site analytics, recently created communities, and community search functionality to the god mode panel. 

https://github.com/hicommonwealth/commonwealth/assets/31940965/6ad71dc8-e15d-48ce-8c05-449fbb1e6978

## Test Plan
- Tested locally.

## Deployment Plan

1. 

## Other Considerations

-

2023-06-05 21:18 UTC, jnaviask requested changes
Small fix then g2g.

2023-06-05 21:18 UTC, jnaviask commented on packages/commonwealth/client/scripts/views/pages/AdminPanel/Analytics.tsx
> +    await $.ajax({
We should use axios instead of jquery.

2023-06-05 21:18 UTC, jnaviask commented on packages/commonwealth/client/scripts/views/pages/AdminPanel/Analytics.tsx
> +      await $.ajax({
Please use axios.

2023-06-06 12:45 UTC, alexyoung23j commented on packages/commonwealth/client/scripts/views/pages/AdminPanel/Analytics.tsx
> +    await $.ajax({
done

2023-06-06 15:15 UTC, merged