[reduces slug size] Moved webpack and babel to devDependencies.
hicommonwealth/commonwealth pull request #4265
Opened 2023-06-15 18:35 UTC by kurtisassad

## Link to Issue
Closes: #4262 

## Description of Changes
- Refactor server.ts in order to break the dependency between webpack and production run.
- Moved webpack and babel adjacent imports into devDependencies
- Added start-external-webpack in order to be able to test the production build locally.

## Test Plan
- Ran start (development build) navigated to different webpages to ensure webpack bundles were served correctly. 
- Ran build-app + start-external-webpack navigated to different webpages to ensure webpack bundles were served correctly.
- Ran on staging (in progress)

2023-06-15 18:36 UTC, kurtisassad commented
Drafted while making sure it works on staging

2023-06-20 10:08 UTC, timolegros requested changes
Tested on Frick because Frack is still on Heroku-20 stack and the Heroku-20 stack has a considerably smaller slug size than Heroku-22. Frick slug size was reduced from 498 MB to 463 MB.

@CowMuon I don't think these changes pose a danger to production as production compiling has not changed (only the local/dev compiling process has been updated).

To test I did the following:
- Deployed to Frick and Frack and observed reduced slug size. Clicked around on Frick (loaded dashboard, loaded osmosis, created a thread, commented on another thread, loaded proposals, and loaded the create community modal).
- Started the local dev server (`yarn start`) and clicked around similarly. Also made some changes to server files to ensure hot reloading was not affected.
- Ran the production build step `yarn build-all` and then used the new `yarn start-external-webpack` to start the server. Clicked around to confirm.

2023-07-03 12:53 UTC, kurtisassad commented on packages/commonwealth/server.ts
> +    if (!NO_CLIENT_SERVER) {
Good catch, fixed.

2023-07-05 17:49 UTC, jnaviask commented
For reference @timolegros, the distinction in slug size is not about the heroku stack version but about frick's usage of the datadog buildpack, which adds ~100 MB to slug size.

2023-07-05 18:13 UTC, timolegros commented
> For reference @timolegros, the distinction in slug size is not about the heroku stack version but about frick's usage of the datadog buildpack, which adds ~100 MB to slug size.

Good to know. Should probably still update the stack though. #4291

2023-08-02 16:24 UTC, jnaviask commented
Any deployment changes required to ship this? @kurtisassad

2023-08-02 16:37 UTC, jnaviask approved these changes
Really good stuff -- love that we can now do production builds locally. Ready to go in whenever.

2023-08-09 19:54 UTC, merged