add on delete cascade notifread to allow sub del
hicommonwealth/commonwealth pull request #4300
Opened 2023-06-21 15:48 UTC by NakulManchanda

## Link to Issue
Closes: #TODO

## Description of Changes
- Adds FIXME widget to TODO page.
- 

## Test Plan
- Unit tested the `FIXME()` call.
- CA (click around) tested on local and frack:
  - TODO page
  - 

## Deployment Plan

1. 

## Other Considerations

-

2023-06-21 17:18 UTC, NakulManchanda commented
Hi @timolegros @CowMuon 

- should we do `ON DELETE SET NULL` instead of `ON DELETE CASCADE` ?

- `ON DELETE CASCADE` - we will mess up ordering of `id` column in NotificationsRead and loose NotifcationHistory
- `ON DELETE SET NULL`  setting subscription_id as NULL - will help with both offset and maintaining history

2023-06-21 20:14 UTC, timolegros commented
I think we can close all PRs related to NotificationsRead since we are entirely removing the table very soon.

2023-08-08 19:24 UTC, jnaviask requested changes
1. Needs down migration -- we need to ensure we can reverse the migration if it fails.
2. Schema changes need to be reflected in the ORM layer = the NotificationsRead model. Reason is we need to ensure that the changes are memorialized as part of the codebase and not just within the database schema / as a migration.

2023-08-08 23:32 UTC, timolegros commented
@jnaviask @NakulManchanda This PR should not be merged as is. The subscriptions foreign key in `NotificationsRead` was dropped in #4410 so this would add it back and cause errors in the database cleaner. Since the foreign key constraint is removed users can now delete subscriptions without errors so this `delete cascade` change is no longer required. That said, to keep the database clean, this PR should instead add a query to the database cleaner to delete `NotificationReads` records that don't have an associated subscription.

2023-08-09 00:02 UTC, NakulManchanda commented
> add a query to the database cleaner to delete NotificationReads records that don't have an associated subscription.

Should we delete "NotificationReads" on subscription delete?
- NotificationRead is generated before we user un-subscribe.
- We should treat "NotificationReads" table as immutable - archiving or cleaning old is fine.
- Display notification in Notification tab, screen we don't need subscription information anyways!

We can just close this PR if foreign key constraint is dropped. It was not needed anyways!

2023-08-10 16:34 UTC, NakulManchanda commented
As reviewed in our parking lot discussion:
There's no need for additional action; the foreign key causing the server error 500 has been removed. Deleting subscriptions no longer causes issues, ensuring users can unsubscribe without complications.

2023-08-10 16:34 UTC, closed without merging