Quill Editor - Design update
hicommonwealth/commonwealth pull request #4359
Opened 2023-06-29 11:29 UTC by masvelio

## Link to Issue
Closes: #TODO

## Description of Changes
- Adds FIXME widget to TODO page.
- 

## Test Plan
- Unit tested the `FIXME()` call.
- CA (click around) tested on local and frack:
  - TODO page
  - 

## Deployment Plan

1. 

## Other Considerations

-

2023-07-01 00:59 UTC, zakhap commented
Looking really good, but didn't get a chance to inspect the pixel details. Will have a more thorough review on monday 👍

2023-07-03 10:47 UTC, masvelio commented
@meeshlin Just realised that the icon for todo list is missing in figma (or I can't find it). Please provide it

![image](https://github.com/hicommonwealth/commonwealth/assets/14819225/1290614f-2f87-4e37-88b1-8508ccd4c641)

2023-07-06 09:24 UTC, masvelio commented
@zakhap @meeshlin phosphor icons added, ready to be re-reviewed

2023-07-06 13:22 UTC, zakhap commented
I think the new icons look fantastic! Thanks for updating them @masvelio!

My one question is around the expected/desired behavior of the Markdown button, is this correct @meeshlin ? If so, I think this PR is ready to go 🔥 

<img width="166" alt="Screen Shot 2023-07-06 at 9 21 35 AM" src="https://github.com/hicommonwealth/commonwealth/assets/16248081/d5677351-1f73-4f70-a6a3-3afd800b365d">
<img width="177" alt="Screen Shot 2023-07-06 at 9 21 37 AM" src="https://github.com/hicommonwealth/commonwealth/assets/16248081/55b01a4d-5e71-4ee3-a581-7999390fb56a">

2023-07-07 12:41 UTC, meeshlin commented
**Design review**
1). The purpose of having a markdown button is so users know that they're writing in markdown and the non-markdown mode should show the text in their markdown edited format (headers would should up as headers without the # seen in markdown). 
2). In markdown mode, the list buttons (bullet, number, and check) aren't working to automatically add the markdown syntax.

**Important fast follows:** 
1). Hide Placeholder copy — it makes sense to have placeholder text built into the component as placeholders are necessary from an accessibility standpoint and for product/feature function clarity, but we need to hide it for now as we don’t have placeholder copy in our editors
2). Add active state for icon buttons ([Figma dev mode file](https://www.figma.com/file/eIVp33a1oCu0AtcLwSbGjr/%F0%9F%9A%A7-Components-and-Patterns?type=design&node-id=1629%3A12277&mode=dev)) 

@masvelio @zakhap

2023-07-07 12:47 UTC, masvelio commented
> 2). In markdown mode, the list buttons (bullet, number, and check) aren't working to automatically add the markdown syntax.

It works but only if you select the text first, which is not ideal. This behaviour exists in the production now (was not introduced in this PR) so I would say that this PR should go in and the bug should be ticketed separately.

2023-07-07 15:12 UTC, zakhap commented
> > 2). In markdown mode, the list buttons (bullet, number, and check) aren't working to automatically add the markdown syntax.
> 
> It works but only if you select the text first, which is not ideal. This behaviour exists in the production now (was not introduced in this PR) so I would say that this PR should go in and the bug should be ticketed separately => #4427

I agree with @masvelio here. Let's get this in and then fix the bug subsequently.

2023-07-10 17:32 UTC, jnaviask requested changes
Please fix merge conflict.

2023-07-10 17:32 UTC, jnaviask commented on packages/commonwealth/client/scripts/views/components/component_kit/cw_component_showcase.tsx
We should adjust this file to use single quotes.

2023-07-10 17:32 UTC, jnaviask commented on packages/commonwealth/client/scripts/views/components/react_quill_editor/react_quill_editor.tsx
> +            className={clsx('QuillEditor', className, {
What does clsx do?

2023-07-10 17:41 UTC, jnaviask commented
Also added #4453 as a known bug present on production. This PR is good to go.

2023-07-10 19:33 UTC, merged