Refresh user dashboard feed section after login
hicommonwealth/commonwealth pull request #4395
Opened 2023-07-03 19:52 UTC by mzparacha

## Link to Issue
Closes: https://github.com/hicommonwealth/commonwealth/issues/3946

## Description of Changes
Refreshes the user dashboard feed sections after login

## Test Plan
1. Go to the /dashboard page
2. Logout then login
3. Verify that the feed sections get updated

## Deployment Plan
When a user logouts on `/dashboard/for-you`, it redirects to `/dashboard/global` which seems like a bad UX. I asked a question for this [here](https://github.com/hicommonwealth/commonwealth/issues/3946#issuecomment-1618732475), awaiting how to move forward here. @CowMuon @jnaviask 

## Other Considerations
N/A

2023-07-11 14:46 UTC, jnaviask requested changes
Logic seems fine but some small issues.

2023-07-11 14:46 UTC, jnaviask commented on packages/commonwealth/client/scripts/views/pages/user_dashboard/index.tsx
> +  const {isLoggedIn} = useUserLoggedIn();
Not linted / formatted properly? Should have spaces around the object destructuring.

2023-07-11 14:46 UTC, jnaviask commented on packages/commonwealth/client/scripts/views/pages/user_dashboard/index.tsx
> +    <div ref={setScrollElement} className="UserDashboard" key={isLoggedIn + ''}>
We should use `${isLoggedIn}` rather than adding to ''.

2023-07-17 19:22 UTC, jnaviask commented
cc @mzparacha to respond to comments / fix

2023-07-18 15:37 UTC, mzparacha commented
Fixed cc: @jnaviask

2023-07-18 17:47 UTC, jnaviask approved these changes

2023-07-18 17:48 UTC, merged