Added github action to draft PR without issue number
hicommonwealth/commonwealth pull request #4430
Opened 2023-07-07 13:20 UTC by kurtisassad

## Link to Issue
Closes: #4258

## Description of Changes
- Adds CI step which will draft a PR if the issue number is not present. 

## Test Plan
- Created a PR without an issue number, watched this CI step turn it into draft
- Created a PR with an issue number (this one), watched CI step keep it open

2023-07-24 18:46 UTC, CowMuon approved these changes
LGTM

2023-07-24 21:30 UTC, jnaviask requested changes
Is there any way to query the PR's metadata for a linked issue, rather than looking at the description?

2023-07-24 21:30 UTC, jnaviask commented on .github/workflows/draft_without_issue.yml
> +            const issueMatcher = /[cC]loses:\s*#(\d+)/;
"Fixes" is also valid -- we shouldn't rely on regex unless we really have no other choice...

2023-12-04 15:32 UTC, Rotorsoft approved these changes
LGTM 🚀

2024-02-07 19:57 UTC, CowMuon approved these changes
✅

2024-02-07 20:02 UTC, jnaviask approved these changes

2024-02-07 20:02 UTC, merged