Client Side Image Compression
hicommonwealth/commonwealth pull request #4517
Opened 2023-07-17 17:26 UTC by alexyoung23j

## Link to Issue
Closes: #4238 

## Description of Changes
- Adds a helper function `compressImage` that uses `browser-image-compression` to compress images to 10MB and max 1000px width or height (the constraints needed for Cloudflare Polish to work). This is used to compress files everywhere we upload to s3- if the file is not an image, it is not compressed and uploaded as normal.

## Test Plan
- Upload an image larger than 10MB or 1000px width/height and then visit the s3 url for the uploaded content, you should see the image has been compressed. 

## Deployment Plan

1. 

## Other Considerations

-

2023-07-17 17:57 UTC, jnaviask commented
@alexyoung23j what were the reasons you ended up going with `browser-image-compression` vs an alternative library?

2023-07-17 19:09 UTC, CowMuon commented
In general, "most of the articles I found were using it" is not exactly the best reason for using a library; but rather why is it that it is so widely used. Do we understand what makes it the best choice, or are we just blindly using it because everyone else is? 

While this is an important engineering principle that we follow, in the case of image resizing, I'm fine with this. However we do need to be surfacing more actual engineering in our engineering.

2023-07-19 15:17 UTC, jnaviask requested changes
How long do we expect compression to take? Do we show any sort of loading dialogue if it takes a long time?

2023-07-19 16:07 UTC, alexyoung23j commented
@jnaviask In my tests I saw no noticeable difference in upload vs compression + upload time, but in the case of quill the UI already has a loading spinner.

2023-07-19 16:13 UTC, alexyoung23j commented on yarn.lock
> +quill@^2.0.0-dev.4:
Hm, im looking now but not totally sure. I didn't touch that package (just added the browser compression package), and just ran yarn from the root. Seems like the version of quill we have in package.json is indeed this 2.0.0-dev.4, but previously was resolving to 1.3.7, and then running yarn changed that? @rbennettcw Do you have any insight about what's happening here?

2023-07-19 16:33 UTC, rbennettcw commented on yarn.lock
> +quill@^2.0.0-dev.4:
I don't think I've ever changed the `quill` dependency. Perhaps the addition of `react-quill` or one of the other quill-related deps required a different version of the base lib. I think the lock file shows not just the explicit deps, but also the indirect as well.

2023-07-19 16:36 UTC, rbennettcw commented on yarn.lock
> +quill@^2.0.0-dev.4:
<img width="1068" alt="CleanShot 2023-07-19 at 09 31 17@2x" src="https://github.com/hicommonwealth/commonwealth/assets/126922418/3f1744a7-540f-4739-b03f-adfda69cbf4d">

Looks like `2.0.0…` has been there for a while though.

2023-07-19 19:29 UTC, jnaviask commented on yarn.lock
> +quill@^2.0.0-dev.4:
We can't just slide in a major version bump... let me try to regenerate the lock file properly.

2023-07-19 19:33 UTC, jnaviask commented on yarn.lock
> +quill@^2.0.0-dev.4:
I just resolved it by downgrading the quill version manually -- we weren't on 2.x before, so we shouldn't specify it in the package.json.

2023-07-19 19:40 UTC, jnaviask approved these changes
Works.

2023-07-19 19:42 UTC, merged

2023-07-20 15:51 UTC, zakhap commented
<img width="1215" alt="Screen Shot 2023-07-20 at 5 49 43 PM" src="https://github.com/hicommonwealth/commonwealth/assets/16248081/6b4df1d3-30a2-403b-b0bf-3de8052052f6">
Why does the uploading spinner show up behind the editor?

2023-07-20 15:55 UTC, CowMuon commented
Looks like a regressing from downgrading Quill? @jnaviask @alexyoung23j

2023-07-20 16:25 UTC, CowMuon commented
@alexyoung23j If this is merely a visual blip we would like to ship and the fix this as a fast follow. For that we need: the following: 

- [ ] Confirm this is a visual blemish, and not an affordance that does anything. (ie user cannot interact with it, no actual functionality is negatively or positively impacted.) 
- [ ] Estimate on time/points needed for fix. _**IF WE CAN DO THIS IN THE NEXT HOUR WE WILL HOLD DEPLOYMENT**_  or if it will take longer, we will ship as a fast follow @alexyoung23j 
- [ ] Confirm this was indeed caused by the commit that fixed the package.json <> yarn.lock conflict over Quill version. Our hypothesis is that was the commit that introduced this bug, we need to validate our hypothesis.

2023-07-20 16:32 UTC, alexyoung23j commented
Confirmed that this doesn't affect functionality and is a visual blemish.

2023-07-20 16:58 UTC, CowMuon commented
I would go ahead and bisect the youknowhat out of it, and post the bad commit here. Will circle back in 30 to decide whether to ship+FF or wait for fix.

2023-07-20 17:55 UTC, rbennettcw commented
@CowMuon ^^ There's the fix in the mentioned PR