Package.json Script Purge
hicommonwealth/commonwealth pull request #5058
Opened 2023-09-12 16:23 UTC by gdjohnson

This branch purges unused script aliases in the `commonwealth/package.json` file. It also removes the relevant documentation.

For context on decisions made, see the discussion thread on #4970. If we want to take a more aggressive approach, and prune further, there are some on-the-fence scripts that were retained due to engineer interest (e.g. some of the Sequelize migration scripts) which could be removed. 

Cleaning up linter scripts has expanded in scope—there's no clear team consensus on which scripts and libraries are used, and we should specifically figure out a linting strategy and remove unwanted packages/aliases then. This will further reduce our count.

Closes: #4893.

2023-09-12 18:42 UTC, jnaviask approved these changes
Off to a great start. Some additional comments to work with:

- Flagging dump-db-limit / load-db-limit (and associated .sql files) for removal, as the NotificationsRead table is sufficiently small for us to simply do a dump of the entire db. We may want to replace it with a yarn dump-all command to get a full dump.
- How is load-db-local diff than load-db? Do we need a load-db-local? Hell, when do we use dump-db-local?
- We may want to consider removing the docker scripts -- not sure how/when we will use them, especially post chain events deprecation. cc @timolegros
-

2023-09-12 19:38 UTC, gdjohnson commented
We're down to 55 scripts... Once linter stuff is audited we'll approach high-40s... Can we get lower... I'm picturing a game of limbo...

2023-09-12 20:01 UTC, timolegros commented
> Off to a great start. Some additional comments to work with:
> 
> * Flagging dump-db-limit / load-db-limit (and associated .sql files) for removal, as the NotificationsRead table is sufficiently small for us to simply do a dump of the entire db. We may want to replace it with a yarn dump-all command to get a full dump.
> * How is load-db-local diff than load-db? Do we need a load-db-local? Hell, when do we use dump-db-local?
> * We may want to consider removing the docker scripts -- not sure how/when we will use them, especially post chain events deprecation. cc @timolegros

- Docker scripts in `commonwealth/package.json` can be removed. We've moved on in favour of running docker scripts locally rather than remotely from root `package.json` via `start-rmq` and `start-redis`.
- Local db scripts were especially useful during the creation of chain-events and removal of chain-event types. These can/should be removed.
- I'm not so sure about removing the partial dumps. The NotificationsRead table may be small now but it could grow significantly. Rather than removing all the different dump types we should consider having a single `dump-db` script which takes an optional argument that is, for example, one of 'all', 'limit', or 'semi' with a default to semi which is what the current `dump-db` script does. Would still allow dumping the entire db via 'all' or getting partial tables via the 'limit' option. The script can take inspiration from the existing `load-db` script which allows loading dumps of different names but defaults to `latest.dump`.

@jnaviask @gdjohnson

2023-09-27 18:09 UTC, jnaviask commented
@gdjohnson are we good to merge this branch, or do we anticipate more changes on it?

2023-09-28 17:23 UTC, gdjohnson commented
@jnaviask Merge is really pending a decision on the above, hence why I tagged ya last week!

The uncontroversial decisions have been acted upon (e.g. removing local db & docker scripts). However, @timolegros's partial dump DB recommendations have not been acted upon, in part because they clashed with your earlier recommendation, and in part because Forest expressed some ambivalence, in stand-up last week, whether writing db scripts was within my purview as documentarian.

I'm happy with anything—just caught in a crossfire of different opinions / recommendations, all from sources either better-qualified or higher-ranking than me to make the call. 

It's a bit silly, because this is such a small-peas decision in the grand scheme of things, and we've probably used as much time talking back-and-forth at this point as it would've taken for me to implement Tim's rec. But here we are! Maybe some meta-level takeaways.

2023-10-05 21:22 UTC, timolegros commented
> @jnaviask At this point, I think we should:
> 
> * Merge
> * Open a ticket for Tim's partial-db recommendations
> 
> Feel free to veto or counter-propose. Just tryna follow the "Close your own ticket" philosophy in our Ways of Working doc.

@gdjohnson I suggest not removing the `limited_dump.sql` script in this PR since it can be extremely useful as the size of the database grows. Paired with #5245 which I just created, we should be able to get a clean `dump-db` interface and `package.json` while maintaining accessibility to useful functions/versions of db dumps.

2023-10-10 12:48 UTC, gdjohnson commented
Thanks, done!

2023-10-10 19:41 UTC, timolegros commented on packages/commonwealth/package.json
>      "test-query": "ts-node server/scripts/testQuery.ts",
`test-query` yarn command + `testQuery.ts` script should be removed.

2023-10-10 19:43 UTC, timolegros requested changes
LGTM just requesting one little additional deletion for a script that should have never made it into the codebase to begin with

2023-10-10 19:43 UTC, timolegros commented on packages/commonwealth/package.json
>      "test-query": "ts-node server/scripts/testQuery.ts",
`test-query` yarn command + `testQuery.ts` script should be removed.

2023-10-11 17:42 UTC, gdjohnson commented
@timolegros Amazing, thanks Tim for the eyeballs. 

Updated!

2023-10-12 14:16 UTC, timolegros approved these changes

2023-10-12 18:08 UTC, gdjohnson commented
Merging, since 2 approvals!

2023-10-12 18:08 UTC, merged