Bridged forum webhook options
hicommonwealth/commonwealth pull request #5065
Opened 2023-09-12 21:45 UTC by alexyoung23j

## Link to Issue
Closes: #4961 

## Description of Changes
- Allows admins to toggle on/off webhook notifications for posts that come from the Discobot. 

## "How We Fixed It"

Introduced a new column on chains to store this setting, updated UI to handle it and updated webhook notifier to handle discobot posts accordingly.

## Test Plan
- Add a discord webhook to your community, and then toggle off (it is default to off already) the new setting in the admin panel. Then create a discobot post, and no webhook event should be fired. Toggle on the setting- a new discobot post will create a webhook event. 

## Deployment Plan

1. 

## Other Considerations

-

2023-09-20 17:55 UTC, jnaviask commented
cc @alexyoung23j to fix integration test

2023-10-03 21:15 UTC, jnaviask commented
Would like @timolegros to look at this PR to make sure it doesn't interact with #5207 + report how we can minimize any potential merge conflicts

2023-10-03 21:42 UTC, timolegros requested changes
Just requesting some minor changes. Overall should be easy to port into #5207.

2023-10-03 21:42 UTC, timolegros commented on packages/commonwealth/server/migrations/20230912211513-discord-webhook-setting.js
> +    return queryInterface.addColumn('Chains', 'discord_webhooks_enabled', {
'discord_webhooks_enabled' is misleading as you are not actually enabling _all_ webhooks for Discord just discobot activity.

2023-10-03 21:42 UTC, timolegros commented on packages/commonwealth/test/integration/emitNotifications.spec.ts
> +      console.log('dude');
Nice logs lmao

2023-10-11 17:21 UTC, jnaviask commented
@timolegros would you be willing to fix the merge conflict / pull the changes from webhookNotifier into the new structure? Then this should be g2g.

2023-10-16 15:05 UTC, timolegros approved these changes
I integrated the original changes into the new Webhook pattern so I can't review my own work on that but everything else works and looks as expected.

2023-10-16 16:34 UTC, rbennettcw commented
@timolegros My only concern is with the migration execution order. Are migrations guaranteed to be executed in alphanumerical order? If so, and there are newer migrations, will this migration be skipped?

There are several migrations that have been merged after 2023/09/12

2023-10-16 17:49 UTC, rbennettcw approved these changes
Apparently the migration date doesn't *have* to be in order.

2023-10-16 19:20 UTC, merged