Migration topic thresholds to group IDs
hicommonwealth/commonwealth pull request #5102
Opened 2023-09-18 20:48 UTC by rbennettcw

## Link to Issue
Closes: #5027

## Description of Changes
- Adds a migration which adds a `group_ids` column to Topics, and creates new Groups based on existing topic thresholds.

## Test Plan
N/A

## Deployment Plan
N/A

## Other Considerations
- Includes changes from the initial gating migration, since that's a dependency

2023-09-19 16:08 UTC, rbennettcw commented
Need #5046 to be merged in before this can be finished– so I can use both `eth_chain_id` and `cosmos_chain_id` to perform the migration from topic thresholds to group requirements.

2023-09-28 01:13 UTC, jnaviask commented
@rbennettcw gonna take some time to review this in depth before merging -- one request beforehand is, can we gate these routes behind a feature flag? Don't want to ship this code and have intrepid pen testers start messing around with groups/requirements.

2023-09-28 18:33 UTC, rbennettcw commented
Added env feature flag, details in test plan. May need to update CI to include the new env.

2023-10-02 11:42 UTC, masvelio reviewed
Could you fix quality checks? Quite few of `...is defined but never used` in this PR

2023-10-03 19:02 UTC, jnaviask requested changes
One functional comment. Otherwise seems generally good.

Am worried about merging immediately, because the migration means that we might get out of sync if token_thresholds are updated before the new system takes effect. Would like for us to brainstorm a path to getting this PR out without losing token threshold updates prior to deployment.

2023-10-03 19:02 UTC, jnaviask commented on packages/commonwealth/server/controllers/server_groups_methods/update_group.ts
> +    await this.models.Membership.destroy({
We only want to destroy memberships if the requirements object gets updated -- pure metadata updates should not destroy memberships.

2023-10-03 21:41 UTC, rbennettcw commented
> One functional comment. Otherwise seems generally good.
> 
> Am worried about merging immediately, because the migration means that we might get out of sync if token_thresholds are updated before the new system takes effect. Would like for us to brainstorm a path to getting this PR out without losing token threshold updates prior to deployment.

That's a valid concern.

I'm thinking of 2 approaches:
1. Split the migration into 2 parts
    - Migration to add the `group_ids` column
       - Merge now
    - Migration to create new groups from topic thresholds
      - Move this migration to another PR, merge later
      - In that PR, we'd also remove the `API_GATING_ENABLED` feature flag to enable gating for everyone?

2. Add logic to the `/setTopicThreshold` route to either create the group + threshold requirement if it doesn't exist, or update the token threshold on the existing group if the group already exists. Essentially doing what the migration does, but for a single topic, on the fly. Still thinking about how this will work after a group's requirements have been customized.

2023-10-10 16:55 UTC, jnaviask commented
Per discussion with @rbennettcw we're going with approach 1.

2023-10-10 19:18 UTC, rbennettcw commented
@jnaviask I've updated the migration to only add the column and not create groups.

Saved the original full migration here for reference: https://gist.github.com/rbennettcw/929c839d88fcd9a69b6c6205a2957c69

Will spin off another PR with the migration to add groups once we're nearing the public release of the gating API.

2023-10-11 16:57 UTC, jnaviask commented on packages/commonwealth/server/controllers/server_groups_methods/update_group.ts
> +    await this.models.Membership.destroy({
cc @rbennettcw awaiting this change still

2023-10-11 16:57 UTC, jnaviask commented on packages/commonwealth/server/routes/groups/update_group_handler.ts
> +  TypedRequestBody,
Unused

2023-10-11 17:17 UTC, jnaviask approved these changes

2023-10-11 17:17 UTC, jnaviask commented
tagging @ianrowan as a second reviewer

2023-10-16 16:26 UTC, ianrowan requested changes
Everything logically LGTM, my comments relate to interfaces that will be slightly updated in my implementation PR. I think it makes sense to pull the interface change into here so we dont miss the `await` mentioned

2023-10-16 16:26 UTC, ianrowan commented on packages/commonwealth/server/controllers/server_groups_methods/refresh_membership.ts
> +  const { isValid, messages } = validateGroupMembership(
This is going to be async function in upcoming changes https://github.com/hicommonwealth/commonwealth/pull/5005
I think it makes most sense for merge order considerations to add and `await` here and update `validateGroupMembership` to return a promise - I'll comment there with more info

2023-10-16 16:26 UTC, ianrowan commented on packages/commonwealth/server/util/requirementsModule/validateGroupMembership.ts
> +): ValidateGroupMembershipResponse {
Update to `Promise<validateGroupMembershipResponse>` to avoid issues with merge order/missing the `await` in the refreshMembership code.

2023-10-16 17:21 UTC, ianrowan approved these changes
Thanks for updating the interface, LGTM now

2023-10-16 17:46 UTC, merged