Fixes formatting bugs on Quill Editor
hicommonwealth/commonwealth pull request #5108
Opened 2023-09-19 12:19 UTC by martins87

## Link to Issue
Closes: #4794 

## Description of Changes
- Shows H1, H2, bold and italic formatting when comment is saved

## "How We Fixed It"

Renders write tags for formatting on h1, h2, bold and italic.

## Test Plan
- CA (click around) tested on local. Added text with the formats quoted above.

2023-09-19 14:03 UTC, masvelio approved these changes
Lgtm! Any reasons for 5 points? Seems to be a bit overestimated?

2023-09-20 17:49 UTC, jnaviask requested changes
Combinations of >1 of bold + italics + strikethrough do not work. It only applies one style.

2023-09-24 11:43 UTC, martins87 commented
> Combinations of >1 of bold + italics + strikethrough do not work. It only applies one style.

Addressed:

![image](https://github.com/hicommonwealth/commonwealth/assets/30223098/b18cb585-8fc5-40c5-979a-b4716fe0cf44)

2023-09-27 17:02 UTC, jnaviask approved these changes

2023-09-27 17:08 UTC, merged