Delete chain fix
hicommonwealth/commonwealth pull request #5168
Opened 2023-09-27 20:52 UTC by alexyoung23j

## Link to Issue
Closes: #5126 

## Description of Changes
- Adds a migration to remove a foreign key constraint that was preventing us from deleting chains that had a Discord bot connected. 

## "How We Fixed It"

Migration, added a cascade delete on the DiscordBotConfig table.

## Test Plan
- Attempt to delete a chain with a discord bot connected via the admin panel. 

## Deployment Plan

1. 

## Other Considerations

-

2023-09-27 20:55 UTC, jnaviask commented
@alexyoung23j does this affect the sequelize model at all? + should we permit discord bot configs that don't satisfy this constraint? Seems like we should consider scope of impact here...

2023-10-03 16:27 UTC, alexyoung23j commented
Fixed model, but otherwise the scope here is pretty isolated- the update just ensures that when a chain is deleted the corresponding discord bot config is also deleted. This will always be the desired behavior afaik.

2023-10-03 16:58 UTC, jnaviask requested changes

2023-10-03 16:58 UTC, jnaviask commented on packages/commonwealth/server/models/discord_bot_config.ts
> +      onDelete: 'CASCADE', // add this line
Can you remove the comment?

2023-10-03 19:52 UTC, jnaviask approved these changes

2023-10-03 20:54 UTC, merged