Docs Improvement: Update Ways-of-Working, ReadMes
hicommonwealth/commonwealth pull request #5213
Opened 2023-10-02 16:40 UTC by gdjohnson

This PR bundles a number of (minor) requested changes to our docs. These changes are enumerated below.

## Link to Issue
Links to, but keeps open, #4800

## Description of Changes
- Update AWS region (flagged by @jnaviask) 
- Add a section to our Package.JSON docs, describing how to add new script documentation (requested by @CowMuon) 
- Document what a "high priority" label means (requested by @jnaviask) 
- Add a glossary to our Wishlist
- Various formatting and legibility improvements

2023-10-11 17:05 UTC, jnaviask requested changes
One typo then OK

2023-10-11 17:05 UTC, jnaviask commented on knowledge_base/wiki/Ways-Of-Working.md
> +You must change the title or description of someone else's Github story or PR without permission.
Must not**

2023-10-11 17:36 UTC, gdjohnson commented
@jnaviask Fixed & ready!

2023-10-12 14:49 UTC, jnaviask approved these changes

2023-10-12 14:50 UTC, merged