Added floating createThread button for mobile discussions page
hicommonwealth/commonwealth pull request #5350
Opened 2023-10-17 19:54 UTC by kurtisassad

## Link to Issue
Closes: #5174

## Description of Changes
- Adds create thread button that floats over text in mobile view
- Removes old create thread button when in mobile view
Old:
<img width="542" alt="Screenshot 2023-10-17 at 12 53 05 PM" src="https://github.com/hicommonwealth/commonwealth/assets/14794654/c04e102f-8147-438a-8aff-dff71b7310b9">

New:
<img width="528" alt="image" src="https://github.com/hicommonwealth/commonwealth/assets/14794654/a816c1c9-e0fa-4452-bc35-25aeadd0ba51">

## Test Plan
- CA

## Other Considerations
- I am not sure the sizing/ spacing for the create thread button

2023-10-17 19:54 UTC, kurtisassad commented
NOTE: Do not accept until we get design/product sign off

2023-10-17 21:41 UTC, dillchen requested changes
Add to Overview page as well

2023-10-17 21:49 UTC, kurtisassad commented
> Add to Overview page as well
Added

2023-10-17 22:04 UTC, dillchen commented
per Kurtis' notes there, we want this also on the community homepage but that's after Community Homepage gets merged in

2023-10-17 22:05 UTC, dillchen approved these changes

2023-10-19 15:56 UTC, Miaplacidus commented
@kurtisassad
Great stuff! Left a couple comments. Also, there's an unneeded import in `HeaderWithFilters`.

2023-10-19 15:56 UTC, Miaplacidus requested changes

2023-10-19 15:56 UTC, Miaplacidus commented on packages/commonwealth/client/scripts/controllers/app/login.ts
> +  } else if (provider === 'apple') {
Is this line required given that an empty object is the default return for the function?

2023-10-20 14:51 UTC, dillchen commented
- right: 12px;
- bottom: 12px;
- level three shadow

2023-10-26 15:54 UTC, Miaplacidus approved these changes

2023-10-26 16:08 UTC, kurtisassad commented on packages/commonwealth/client/scripts/views/pages/user_dashboard/index.tsx
Yeah removed. We want to add creation of a thread on the user_dasboard in the future, but not in this PR.

2023-11-30 18:12 UTC, mhagel commented
has conflicts and approvals

2023-12-01 19:36 UTC, merged