refactor WIP
hicommonwealth/commonwealth pull request #5408
Opened 2023-10-20 17:30 UTC by rbennettcw

## Link to Issue
Closes: #5317 (server controllers refactor)
Closes: #5356 (groups table)
Closes: #5357 (polls table)

## Description of Changes
Replaces "chain" with "community" for the following:
- Server controllers and related routes
- Groups model/table (migration)
- Polls model/table (migration)

## Test Plan
TBD

## Deployment Plan
- Run migration

## Other Considerations
N/A

2023-10-25 15:51 UTC, CowMuon approved these changes
low key thrilling to see 93 files updated for a 1 pointer.

2023-10-25 17:01 UTC, timolegros requested changes
`create_community.ts` contains references to chain that haven't been updated:
- `CreateCommunityResult.chain`
- `existingBaseChain`
- `oldChain`
- Errors
- returns `{ chain: chain.toJSON, ... }

Unlike model changes, variable changes don't need to be so large (and therefore hard to correctly review).  For future server-side PRs please try to keep them as small as possible so it is very easy to review e.g. a few routes per PR. This is especially true because review for these PRs involves inspecting `chain` strings in every edited/dependent file. I'd rather review 3-4 PRs with well-defined scopes than 1 large one.

I've reviewed about half the files but I need to step out so posting this review as is for now. Will review the other half later tonight.

2023-10-25 17:19 UTC, rbennettcw commented on packages/commonwealth/client/scripts/controllers/server/polls.ts
> +        chain: communityId,
Sure that makes sense.

2023-10-25 17:20 UTC, rbennettcw commented on packages/commonwealth/server/controllers/server_communities_methods/delete_community.ts
>      throw new AppError(Errors.NeedChainId);
Yeah, we might as well go all the way

2023-10-25 20:34 UTC, timolegros requested changes
- Missing all updates in `server_proposals_controller.ts`.
- Missing updates in `update_community.ts` (mainly `chain` variable that is referenced throughout).

This completes the second half of my review. Focused mostly on updates that were missing. Once the requested changes are implemented I will re-review and focus only on the included changes which I suspect won't result in many (if any) updates.

2023-11-02 21:40 UTC, rbennettcw commented
So many rippling changes 😅 – This is nearly done, I'm currently:
- Updating response payloads to return community instead of chain, where applicable
- Updating the chain validation middleware to support both `chain` and `community` param variations so we can transition
- Updating the frontend axios calls accordingly

It's still scoped to the same routes, but more thorough.

2023-11-06 19:11 UTC, lzach83 commented
I've tested everything I knew how and followed the test plan. Looks great and can't find anything that's broken.

2023-11-06 21:21 UTC, timolegros requested changes
- redirection is broken when creating an ERC20 or ERC721 community. It goes to `http://localhost:8080/undefined` even though the community was successfully created.
- ~~Getting 400 error when trying to update a topic~~ -> this issue is also on master: #5593
- Can't select topics to connect in Discordbot settings on manage community page

2023-11-06 22:55 UTC, timolegros approved these changes

2023-11-06 22:55 UTC, merged