Fixed prettier script
hicommonwealth/commonwealth pull request #5551
Opened 2023-11-02 13:20 UTC by kurtisassad

## Link to Issue
Closes: #5550

## Description of Changes
- Simplified prettier script making it run faster

## "How We Fixed It"
So the xargs -I creates a buffer to store, search and replace the string passed in. This seems to be the cause of the issue because when I remove this option, the script runs as fast as before.

Although to fix this, I just removed the whole pipe chain completely, as prettier takes in a list of files anyways.

## Test Plan
- Run the prettier script on some files. Make sure that the time per file ~50ms

2023-11-02 13:58 UTC, Rotorsoft requested changes
The problem I see with this approach is that $FILES could be too long, and it will fail the hook

Can you try this?

```
#!/bin/bash

GRAY='\033[30m'  
RED='\033[31m' 
YELLOW='\033[33m'
NC='\033[0m' 

FILES=$(git diff --staged --name-only --diff-filter=d | sed 's| |\\ |g')

if [ -n "$FILES" ]
then
    echo -e -n $YELLOW
    echo -e "📐 prettier staged before commit..."
    echo "------------------------------------"
    echo -e $NC
    echo "$FILES" | xargs npx prettier --write --ignore-unknown 
    echo "$FILES" | xargs git add
    exit 0
fi
```

2023-11-02 14:06 UTC, kurtisassad commented
Swapped out to rogers method as:
1. xargs without -I doesn't add too much overhead
2. It fails on windows if too many files are passed in (xargs breaks it up line by line, so it should never fail due to too many files)

2023-11-02 14:07 UTC, Rotorsoft approved these changes
🚀 

Using this option: [https://prettier.io/docs/en/precommit.html#option-5-shell-script]( https://prettier.io/docs/en/precommit.html#option-5-shell-script)

Once we decide to move eslint to pre-commit stage, we can use [lint-staged](https://prettier.io/docs/en/precommit.html#option-1-lint-stagedhttpsgithubcomokonetlint-staged)

2023-11-02 16:36 UTC, Rotorsoft commented on scripts/pre-commit.sh
> -FILES=$(git diff --staged --name-only --diff-filter=d)
why not keeping this comment for later?

2023-11-03 16:41 UTC, Rotorsoft commented
hey @timolegros , can you approve this one? Thanks!

2023-11-03 18:40 UTC, timolegros commented
> hey @timolegros , can you approve this one? Thanks!

Testing it out now will approve in a few minutes if it checks out.

2023-11-03 19:14 UTC, timolegros approved these changes
Confirmed that it ran faster but unable to properly recreate the original issue of merging master. Approving since this is an improvement in performance regardless.

2023-11-03 19:23 UTC, merged