5569-componentSemantics
hicommonwealth/commonwealth pull request #5571
Opened 2023-11-02 21:08 UTC by lzach83

## Link to Issue
Closes: #5569 

## Description of Changes
- Changes `chain` and `chainId` to `community` and `communityId` and everything similar  
## "How We Fixed It"

## Other Considerations

- Some files were not touched most glaring is `ProfileActivityRow` which is heavily reliant on the models /types which will be addressed in #3775

2023-11-06 13:33 UTC, masvelio reviewed
![image](https://github.com/hicommonwealth/commonwealth/assets/14819225/fdeee2e6-022c-4e40-a468-b32d7dc6693c)

Look for every usage of <User> component in the codebase and change everywhere `userChainId` to `userCommunityId`

2023-11-06 17:19 UTC, lzach83 commented
Fixed the CR comments. Thank you as always @masvelio 

#5387 should take precedence over this.

2023-11-06 23:34 UTC, timolegros requested changes
Missing changes:
- `const chain`, `chainScope` in `CWSearchBar.tsx`
- `const chainInfo` in `SearchBarCommunityPreviewRow.tsx`
- `chainId` parameter of `useNewThreadForm` function in `useNewThreadForm.ts`

2023-11-06 23:34 UTC, timolegros commented on packages/commonwealth/client/scripts/views/pages/notifications/notification_row_components.tsx
> +    chainId,
`communityId` -> `chainEvent.chain` is a community (not a blockchain).

2023-11-07 10:21 UTC, masvelio approved these changes

2023-11-07 20:59 UTC, lzach83 commented
We're good re-review this.

2023-12-12 10:34 UTC, timolegros approved these changes
Fixed:
- `chainValidationSchema` should not be updated to `communityValidationSchema` because the selectable options are 'solana', 'polkadot', 'ethereum', etc all of which are chains and not communities
- `ProfileActivityRow` had a `chain` prop that wasn't cast to `communityId`. The prop cannot be updated because it is extracted from a `Thread` or `CommentWithAssociatedThread` object. Once those 2 are updated the underlying prop can be updated to `communityId` as well.
- Links for comments and threads broken in search

Tested:
- edit comment
- view user pop-up
- join a new community
- create a new thread using thread form
- view your profile and another users profile
- react on a thread and comment
- view community explore page
- view user avatars
- sign in with a variety of wallets
- Search for communities, members, and threads -> #5960 
- View aave proposals page and a specific proposal page with votes (dydx)
- View the members page
- Edit collaborators -> #5962 
- Use a poll
- View notifications and notification settings page
- View topics list dropdown
- View the user dashboard
- Update users to admins or moderators
- View compound proposals (tribe)

2023-12-12 10:35 UTC, merged