5589 community semantics - Hooks
hicommonwealth/commonwealth pull request #5594
Opened 2023-11-06 22:03 UTC by lzach83

## Link to Issue
Closes: #5589 

## Description of Changes
- Navigated through the `/hooks` dir and make the applicable changes  

## "How We Fixed It"

## Test Plan
- The main changes were around groups and search, ensure both features are working as intended.

2023-11-08 00:20 UTC, timolegros requested changes
Missing changes:
- `const chain` and `allChains` in `useWallets.tsx`
- `chainsData` in `useSearchResults.ts`

2023-11-09 10:56 UTC, masvelio commented on packages/commonwealth/client/scripts/views/pages/search/search_bar.tsx
> +};
wondering why this file is marked as newly created?

2023-11-09 10:57 UTC, masvelio approved these changes
clicked around and works fine. Codewise also looks good

2023-12-05 15:21 UTC, timolegros approved these changes

2023-12-05 15:21 UTC, merged