5397 - Patch for callout banner
hicommonwealth/commonwealth pull request #5638
Opened 2023-11-08 21:47 UTC by lzach83

## Link to Issue
Closes: #5397 -- again

## Description of Changes
- Implemented a call out banner on threads to show gated threads

## "How We Fixed It"

- Gathered all of the groups with the current topic and rendered the banner based on if the current user is a member.

## Test Plan
- Make a group 
- Test that the banner shows for those topic(s)

## Other Considerations

![image](https://github.com/hicommonwealth/commonwealth/assets/35875283/7ba7f071-a9f1-49f1-9ae4-d35c88ff371b)

2023-11-08 23:49 UTC, Miaplacidus requested changes

2023-11-08 23:49 UTC, Miaplacidus commented on packages/commonwealth/client/scripts/views/components/NewThreadForm/NewThreadForm.tsx
> +    return memberFilter.length > 0 && !isMember;
I think just `!isMember` would be adequate here.

2023-11-09 13:43 UTC, mzparacha commented on packages/commonwealth/client/scripts/views/components/NewThreadForm/NewThreadForm.tsx
> +                disabledActionsTooltipText || 'Join community to submit'
this will show `Join community to upvote` instead of `Join community to submit`

2023-11-09 13:44 UTC, mzparacha commented on packages/commonwealth/client/scripts/views/components/NewThreadForm/NewThreadForm.tsx
> +  const showGatingBanner = useMemo(() => {
we can remove this condition and just directly use `restrictedTopicIds.includes(threadTopic.id)` with some state var for closing the banner

2023-11-09 13:44 UTC, mzparacha commented
> Mirroring the solution for when a user is signed out but on the create thread form page, we should show an inline Callout when the user is not in the required Group for the Topic that they selected. If the user selects a Topic they can post in, the Callout should not appear. If they change the Topic to a topic they are not in the required Group for, the Callout will appear.

1. The banner show's regardless if I select the gated topic or not
2. Not closing by clicking the close button (as @masvelio already mentioned above)

2023-11-09 15:02 UTC, lzach83 commented on packages/commonwealth/client/scripts/views/components/NewThreadForm/NewThreadForm.tsx
> +              onClose={() => !!showGatingBanner}
This is embarrassing, what? Who wrote this? 

i'll fix now.

2023-11-09 23:34 UTC, jnaviask approved these changes

2023-11-09 23:36 UTC, jnaviask requested changes
Getting `Cannot read properties of null (reading 'id')` when I go to the new thread page on ideamarket.

2023-11-10 13:01 UTC, mzparacha commented on packages/commonwealth/client/scripts/views/components/NewThreadForm/NewThreadForm.tsx
> +              <CWBanner
We can make this banner a single component since it's used in multiple places -- for the gated group labels we can make a prop.

2023-11-10 13:02 UTC, mzparacha commented on packages/commonwealth/client/scripts/views/components/NewThreadForm/NewThreadForm.tsx
> -  });
we have to keep this

2023-11-10 13:03 UTC, mzparacha commented on packages/commonwealth/client/scripts/views/components/NewThreadForm/NewThreadForm.tsx
> +  const restrictedTopicIds = memberships
yesterday we updated this implementation and now we can remove this and use this
```
const isTopicGated = !!(memberships || []).find((membership) =>
      membership.topicIds.includes(threadTopic?.id),
    );
    const isActionAllowedInGatedTopic = !!(memberships || []).find(
      (membership) =>
        membership.topicIds.includes(threadTopic?.id) && membership.isAllowed,
    );
    const isRestrictedMembership = isTopicGated && !isActionAllowedInGatedTopic;
```

there is some sample code in `handleNewThreadCreation` of this file

2023-11-10 13:04 UTC, mzparacha requested changes
Needs some changes

2023-11-10 19:13 UTC, mzparacha commented
Superseded by https://github.com/hicommonwealth/commonwealth/pull/5695

2023-11-10 19:13 UTC, closed without merging