Docs Improvement: Update Heroku Entry
hicommonwealth/commonwealth pull request #5793
Opened 2023-11-28 23:39 UTC by gdjohnson

When revamping our Commonwealth package ReadMe, as part of our [Onboarding Docs](https://github.com/hicommonwealth/commonwealth/issues/4999) push, I purged the Heroku & DataDog sections. Per consultation with Timothee, much of this information was (1) out of date (2) not especially relevant to new engineering hires.

However, rather than leave these areas undocumented, Tim & I have been meeting to work through how we use these tools, creating new knowledge base entries with up-to-date documentation. This is the first installment (Heroku); DataDog will likely come sometime next week.

Down the line (aspirationally), we would also have documentation our existing Heroku configuration, so that we could set up a new instance from scratch should the need arise. We're not there yet—I'd be curious to hear whether @jnaviask thinks this would be a valuable use of time currently. I also recall hearing whispers that we might move off Heroku in the near-future, which makes me hesitant to spend any more time documenting it than I already have.

## Link to Issue
Links to, but keeps open, #4800.

2023-11-29 21:52 UTC, CowMuon approved these changes
Fine with this going in as is, OTN would like to see (1) demo environment referenced in context of frick/frack/qa env's so everyone understands what each environment is for. 

(2) Do we have explicit instructions on our traffic control system (updating topic in #eng-infra)? 

(3) As a nice to have, alongside/supplementing how-we-use herroku with what's wrong with heroku for us, documenting the specific limitations & pain points that make us wish to get off PAAS onto IAAS.

2023-12-01 18:37 UTC, mw2000 approved these changes

2023-12-01 18:37 UTC, Rotorsoft approved these changes
LGTM - with ongoing refinements

2023-12-01 18:45 UTC, timolegros commented on knowledge_base/Testing-Environments.md
> +Currently we have 2 open testing environments in Heroku for testing any third party integrations requiring a direct connection, called "Frick" and "Frack" and located at `https://commonwealth-frick.h
Now that CE 2.0 has been deployed _all_ environments have access to chain-events (Frack included).

2023-12-01 18:50 UTC, timolegros requested changes

2023-12-01 18:50 UTC, timolegros commented on knowledge_base/Testing-Environments.md
> +Currently we have 2 open testing environments in Heroku for testing any third party integrations requiring a direct connection, called "Frick" and "Frack" and located at `https://commonwealth-frick.h
Now that CE 2.0 has been deployed all environments have access to chain-events (Frack included).

2023-12-01 18:50 UTC, timolegros commented on knowledge_base/Heroku.md
> +5. `commonwealth-frack`: a standalone raw Common instance that doesn't interact with other services; it is used for testing pure UI.
Frack can be used for general API or migration testing as well --- main distinction from Frick is that it simply doesn't have connected services.

2023-12-01 18:50 UTC, timolegros commented on knowledge_base/Testing-Environments.md
> +We also have a QA environment which is automatically updated whenever feature branches are merged to master, which is located at `https://commonwealth-beta.herokuapp.com.` However, this QA environmen
Same with chain-events here.

2023-12-01 18:50 UTC, timolegros commented on knowledge_base/Heroku.md
> +Heroku procfiles are used to specify the processes (workers, dynos, resources) executed by an app on startup. Processes of the "release" type are run during the [release phase](#release-phases). See
May be worth mentioning here that we have a `multi-procfile` setup (which also means we use a multi-procfile buildpack): https://github.com/heroku/heroku-buildpack-multi-procfile

2023-12-01 18:50 UTC, timolegros commented on knowledge_base/Heroku.md
> +The `common-app` comprises several sub-apps or servers:
The proper terminology here is that technically `common-app` is a pipeline and then all the apps within it are different stages of the pipeline.

2023-12-06 22:46 UTC, jnaviask commented
cc @timolegros to re-review, then we can get these changes in

2023-12-06 23:31 UTC, timolegros approved these changes

2023-12-06 23:32 UTC, merged