Optimize balance fetching for refresh route
hicommonwealth/commonwealth pull request #6145
Opened 2023-12-22 05:36 UTC by rbennettcw

## Link to Issue
Closes: #6012

## Description of Changes
- Optimizes the `/refresh-membership` route to *not* fetch balances for fresh memberships– this will ultimately make gated actions snappier because it prevents unecessary fetching

## "How We Fixed It"
- Check membership state before performing batch fetch

## Test Plan
- TBD

## Deployment Plan
N/A

## Other Considerations
N/A

2024-01-03 21:05 UTC, timolegros requested changes
The membership `last_checked` value does not refresh if I comment on my own thread (regardless of how long I wait). Is this normal? Works as expected elsewhere.

2024-01-03 21:10 UTC, rbennettcw commented
> The membership `last_checked` value does not refresh if I comment on my own thread (regardless of how long I wait). Is this normal? Works as expected elsewhere.

Yep, expected since gating check is bypassed for threads you own. I should have clarified in the test steps.

2024-01-03 21:21 UTC, timolegros approved these changes

2024-01-04 21:42 UTC, ianrowan approved these changes
Looks good

2024-01-04 21:59 UTC, merged