Update Datadog Docs
hicommonwealth/commonwealth pull request #6183
Opened 2024-01-02 23:20 UTC by gdjohnson

Previously, our Datadog documentation was housed in the ReadMe. It was removed as part of our onboarding cleanup (#5521). 

The forked entry remained out-of-date, missing critical information, and providing obsolete or misleading info. In consultation with @timolegros, the entry has been overhauled. 

The existing configuration walk-through has been cleaned up for greater clarity, and several new sections have been added, providing (1) an overview to the Datadog dashboard (2) information on our Postgres/Redis/RabbitMQ integrations, and (3) listing various quirks of Heroku's logging and Datadog integration.

## Link to Issue
Links to, but keeps open, #4800.

## Description of Changes
- Updates `Datadog.md`
- Adds TOC entry

2024-01-03 00:00 UTC, timolegros requested changes
Small change.

2024-01-03 00:31 UTC, gdjohnson commented on knowledge_base/Package-Scripts.md
>  Definition: `chmod u+x scripts/setup-datadog-postgres.sh && ./scripts/setup-datadog-postgres.sh`
Amazing, thanks so much, will merge in

2024-01-03 19:25 UTC, timolegros approved these changes

2024-01-07 19:37 UTC, CowMuon approved these changes
⭐️

2024-01-07 19:37 UTC, merged