6201-Fixed profile navigation bug
hicommonwealth/commonwealth pull request #6207
Opened 2024-01-04 16:15 UTC by lzach83

## Link to Issue
Closes: #6201 

## Description of Changes
- Switched the use of jQuery to Axios for API call
- Added an `AbortController` to handle any potential memory leaks and preventing state updating unnecessarily 

## "How We Fixed It"

- Added `profileId` as a dependency to the `useEffect`
- Switched the jQuery call to Axios
- Added an AbortController to the call within the `useEffect`

## Test Plan
- Visit another person's profile
- Click "Visit Profile" from the top right dropdown

2024-01-05 16:44 UTC, Miaplacidus requested changes

2024-01-05 16:44 UTC, Miaplacidus commented on packages/commonwealth/client/scripts/views/components/Profile/Profile.tsx
> +        signal,
Are we aborting the request immediately here? If so, why?

2024-01-05 16:52 UTC, Miaplacidus approved these changes

2024-01-08 22:07 UTC, Israellund approved these changes
LGTM

2024-01-08 22:11 UTC, merged