Adopt TS project references
hicommonwealth/commonwealth pull request #6228
Opened 2024-01-05 19:36 UTC by Rotorsoft

Restructures monorepo with incremental builds and consolidated scripts

## Link to Issue
Closes: #6197

## Description of Changes
- Updated Package_Scripts.md
- 

## "How We Fixed It"
-

2024-01-07 14:59 UTC, Rotorsoft commented
@timolegros @jnaviask - What are your thoughts about creating a naming convention standard for service scripts? We are using `start` for dev mode and also production mode (start-all, start-consumer, start-prod-listener, etc). 

Do you think it would help to separate scripts in `dev` mode (with watchers, ts-node..., etc) from `production` mode (transpiled, node app.js, etc)?

This is the convention I've used before:

- `dev`: This script is often used for running the application in development mode. Developers can use npm run dev or yarn dev to start the application with additional tools, features, or configurations for development.

- `test`: Used for running test suites. Developers can run npm test or yarn test to execute the project's test suite.

- `build`: This script is often used to build the project for production. Running npm run build or yarn build would typically compile and prepare the project for deployment.

- `start`: This is typically used to run the application in production mode. When someone runs npm start or yarn start, it should start the application as it would run in a production environment.

2024-01-07 19:47 UTC, CowMuon commented
How is our slug size doing? @jnaviask @kurtisassad

2024-01-07 19:49 UTC, CowMuon approved these changes
This all looks fine for me. Definitely would like to get @gdjohnson 's feedback and signoff here if nothing got missed.

2024-01-08 14:40 UTC, kurtisassad commented on scripts/heroku-build.sh
Whats the purpose of this file given that we already have scripts/build.sh.

Both of these will only be used on heroku so I am unsure why we need both. Is there some other use-case you had in mind?

2024-01-08 14:46 UTC, Rotorsoft commented on scripts/heroku-build.sh
Yes, there is a slight difference. `build` is more generic, can be used  in local dev mode, CI, and deployments (heroku).... `heroku-build` extends build with a cleanup step that only applies to heroku.

2024-01-08 15:07 UTC, kurtisassad commented on scripts/heroku-build.sh
But is it necessary? I think we should keep our production build as similar as possible across the CI and Heroku. Otherwise we will run into issues where the CI or local won't catch potential issues, which will force us to test on heroku. We should strive to keep the developer feedback loop as small as possible.

2024-01-08 15:31 UTC, kurtisassad approved these changes

2024-01-08 16:24 UTC, timolegros commented
> @timolegros @jnaviask - What are your thoughts about creating a naming convention standard for service scripts? We are using `start` for dev mode and also production mode (start-all, start-consumer, start-prod-listener, etc).
> 
> Do you think it would help to separate scripts in `dev` mode (with watchers, ts-node..., etc) from `production` mode (transpiled, node app.js, etc)?
> 
> This is the convention I've used before:
> 
> * `dev`: This script is often used for running the application in development mode. Developers can use npm run dev or yarn dev to start the application with additional tools, features, or configurations for development.
> * `test`: Used for running test suites. Developers can run npm test or yarn test to execute the project's test suite.
> * `build`: This script is often used to build the project for production. Running npm run build or yarn build would typically compile and prepare the project for deployment.
> * `start`: This is typically used to run the application in production mode. When someone runs npm start or yarn start, it should start the application as it would run in a production environment.
> 
> CC: @gdjohnson, @CowMuon - just a small detail, but since I'm looking at the scripts in this and my next PR, maybe this is the opportunity to tackle any pending items in our wishlists.

I'm all for this as long as this doesn't mean we remove service-specific commands e.g. `yarn start-consumer` -> `yarn dev-consumer`. Saying this because these services are secondary and rarely necessary for developing on commonwealth so it's unnecessary to run them as part of `yarn dev` (that or `yarn dev` runs everything and we have a `yarn dev-app` that replaces `yarn start`).

A standard syntax for creating scripts should be included as well. We have some scripts defined as `yarn [scope]:[command]` vs `yarn [scope]-[command]`. Let's pick one and run with it.

2024-01-08 16:34 UTC, timolegros approved these changes
Assuming this builds/deploys correctly on Heroku Frick/discobot it looks good to me apart from the tiny doc change.

2024-01-08 16:34 UTC, timolegros commented on knowledge_base/Link-Previews.md
> +    NO_TOKEN_BALANCE_CACHE=true NO_PRERENDER=true NO_CLIENT_SERVER=true MIXPANEL_DEV_TOKEN=foo MIXPANEL_PROD_TOKEN=bar NODE_ENV=production npx ts-node -T -r tsconfig-paths/register server.ts
This was removed in a previous PR - should not be added back
```suggestion
    NO_PRERENDER=true NO_CLIENT_SERVER=true MIXPANEL_DEV_TOKEN=foo MIXPANEL_PROD_TOKEN=bar NODE_ENV=production npx ts-node -T -r tsconfig-paths/register server.ts
```

2024-01-08 16:58 UTC, merged

2024-01-08 16:58 UTC, gdjohnson requested changes
Thanks for taking the time to update the docs Roger.

I suggested some formatting/organization tweaks to the `Package-Scripts.md` file. Main thing is keeping the script names as headers (rather than having separate header name + script name).

As always, I'm very open to proposals for re-organizing knowledge base docs—especially as they're lived in and updated and we better understand needs/uses—but I want to keep entropy low in the meantime by keeping layout super uniform across docs, and preventing the proliferation of style variants.

Thanks for the tag @CowMuon! And thanks again Roger for all your help with the docs!

2024-01-08 16:58 UTC, gdjohnson commented on knowledge_base/Package-Scripts.md
> +## Application Build
```suggestion
## build
```

2024-01-08 16:58 UTC, gdjohnson commented on knowledge_base/Package-Scripts.md
> +Script: `yarn build`
```suggestion
```

2024-01-08 16:58 UTC, gdjohnson commented on knowledge_base/Package-Scripts.md
> +## CI Build
```suggestion
## build-ci
```

2024-01-08 16:58 UTC, gdjohnson commented on knowledge_base/Package-Scripts.md
> +Script: `yarn build-ci`
```suggestion
```

2024-01-08 16:58 UTC, gdjohnson commented on knowledge_base/Package-Scripts.md
> +## Heroku Build
```suggestion
```

2024-01-08 16:58 UTC, gdjohnson commented on knowledge_base/Package-Scripts.md
> +### heroku-prebuild
```suggestion
## heroku-prebuild
```

2024-01-08 16:58 UTC, gdjohnson commented on knowledge_base/Package-Scripts.md
> +### heroku-postbuild
```suggestion
## heroku-postbuild
```

2024-01-08 16:59 UTC, gdjohnson commented
Woof, looks like I missed review by a matter of minutes—I can open a separate PR then to update.

2024-01-08 21:10 UTC, timolegros commented
@Rotorsoft we made a big mistake here. By changing the `include` portion of `commonwealth/tsconfig.json` type checking was entirely removed from the client. That means `yarn check-types` no longer detects critical type errors on the client whatsoever. This needs to be fixed ASAP before we accidentally push broken client-side code to master.