Manage Staking [draft]
hicommonwealth/commonwealth pull request #631
Opened 2020-08-23 19:50 UTC by mir-nawaz

## Description
Manage to stake, add nominators, and validate. 

## Motivation and Context
Add new nominators and validate nodes. 

## How has this been tested?
Tested with local edgeware to test for all transactions.

## Have proper tags been added (for bug, enhancement, breaking change)?
- [x] yes

## Does this PR affect any server routes?
- [ ] yes, and they are tested: [enter the % coverage here]
- [ ] yes, and they are not tested: [enter the % coverage here]
- [ ] yes, but I did not run tests
- [x] no

2020-08-27 17:58 UTC, drewstone commented
@mir-nawaz I'd rebase against staking-ui now that the merge from master has gone in. It looks like this carries a lot of extra work over that I don't want to have to review again.

2020-09-02 21:55 UTC, drewstone commented
@raykyri this is a lot of UI work too so would be great to take a look.

2020-09-06 18:07 UTC, mir-nawaz commented on client/scripts/controllers/chain/substrate/staking.ts
> +  public get validatorsAddress(): Observable<string[]> {
Yes, You are right. But it's not included in this feature. @iqraabdulrauf is working on it, So I'll leave a comment to integrate in the future.

2020-09-07 04:24 UTC, drewstone requested changes

2020-09-11 10:50 UTC, mir-nawaz commented on client/scripts/controllers/chain/substrate/shared.ts
>            this._tokenDecimals = +tokenDecimals.unwrapOr(12);
Not sure, this is from legacy code. Can't find DEFAULT_TOKEN_DECIMALS anywhere.

2020-09-15 14:58 UTC, merged