Add sanity script
hicommonwealth/commonwealth pull request #6321
Opened 2024-01-10 20:55 UTC by Rotorsoft

Adds sanity script to check code quality before pushing to remote

## Link to Issue
Closes: #6200

## Description of Changes
- Adds sanity script (can be expanded with more steps)

2024-01-10 21:00 UTC, rbennettcw approved these changes

2024-01-11 16:40 UTC, gdjohnson requested changes
Suggested some added words—if they're not quite right feel free to tweak/reject.

Maybe of note that you have to `yarn build` before `sanity` works without erroring out?

I'm on a new machine (my laptop got lost for ~a month and has now returned to me) so I hadn't run a build yet. Maybe this won't be a problem for most engineers most of the time, and the error logs do indicate missing build files, but thought I'd flag in case.

2024-01-11 16:40 UTC, gdjohnson commented on knowledge_base/Package-Scripts.md
> +Description: Sanity scripts developers should run locally before pushing code
```suggestion
Description: Sanity scripts developers should run locally before pushing code, comprising a linter, a check-types, and unit tests. Must be run from root.
```

I agree we should move towards running scripts from root, but in the meantime might be worth explicitly noting which scripts must be run root

2024-01-11 18:27 UTC, gdjohnson approved these changes

2024-01-11 18:28 UTC, merged