Israel.5490.governance mixpanel
hicommonwealth/commonwealth pull request #6604
Opened 2024-02-06 20:28 UTC by Israellund

## Link to Issue
Closes: #5490

## Description of Changes
Added Mixpanel Analytics to Snapshot voting and Governance proposals & voting. Changed logic withink onClicks to conform to updated code standards
NOTE: There was already a Snapshot Creation Mixpanel event in the codebase so I did not add to the first checkbox. And I was unable to test on the on-chain proposals, as there is no testnet available for that. 

## Test Plan
NOTE: Only Snapshot creation and votes are able to be tested as there is no testnet for the on-chain proposals. 
-Create a Snapshot
-Confirm in Mixpanel that this occurred
-Cast a vote on a Snapshot
-Confirm in Mixpanel that this occurred.

2024-02-07 12:01 UTC, masvelio commented on packages/commonwealth/client/scripts/views/modals/confirm_snapshot_vote_modal.tsx
> +          onClick={handleVote}
good stuff!

2024-02-07 12:02 UTC, masvelio commented on packages/commonwealth/client/scripts/views/modals/confirm_snapshot_vote_modal.tsx
> +    });
event will be fired regardless success or failure. Shouldn't it be only at the end of `try` cluase?

2024-02-07 12:02 UTC, masvelio commented on packages/commonwealth/client/scripts/views/components/proposals/voting_actions.tsx
> +      });
same here, shouldn't it be before catch?

2024-02-07 12:03 UTC, masvelio commented on packages/commonwealth/client/scripts/views/components/proposals/voting_actions.tsx
> +      });
and here

2024-02-07 12:04 UTC, masvelio commented on packages/commonwealth/client/scripts/views/pages/new_proposal/sputnik_proposal_form.tsx
> +      <CWButton label="Send transaction" onClick={handleSendTransaction} />
thanks for moving all of these inline functions into the handlers! This way we declutter jsx/visual part of the code

2024-02-07 12:05 UTC, masvelio commented on packages/commonwealth/client/scripts/views/pages/new_proposal/aave_proposal_form.tsx
> +    //   .catch((err) => notifyError(err.data?.message || err.message));
what about this? It was not commented out

2024-02-07 12:06 UTC, masvelio approved these changes
didn't test if works with mixpanel. Few small comments to the code but generally looks good 💪

2024-02-07 14:04 UTC, Israellund commented
@masvelio Just pushed changes, thanks for catching those. I guess I went a little cross-eyed looking at so many else if and try/catch statements.

2024-02-07 19:17 UTC, jnaviask requested changes
Any way to at least confirm these pages render correctly? What communities did you use?

2024-02-07 19:17 UTC, jnaviask commented on packages/commonwealth/client/scripts/views/modals/confirm_snapshot_vote_modal.tsx
> +import { formatNumberShort } from '../../../../shared/adapters/currency';
Please don't use relative imports for these.

2024-02-07 19:17 UTC, jnaviask commented on packages/commonwealth/client/scripts/views/pages/new_proposal/aave_proposal_form.tsx
> +import { useBrowserAnalyticsTrack } from 'client/scripts/hooks/useBrowserAnalyticsTrack';
Remove client/scripts prefix.

2024-02-07 19:17 UTC, jnaviask commented on packages/commonwealth/client/scripts/views/pages/new_proposal/aave_proposal_form.tsx
> +import { MixpanelGovernanceEvents } from '../../../../../shared/analytics/types';
Use absolute import.

2024-02-07 19:17 UTC, jnaviask commented on packages/commonwealth/client/scripts/views/pages/new_proposal/compound_proposal_form.tsx
> +import { useBrowserAnalyticsTrack } from 'client/scripts/hooks/useBrowserAnalyticsTrack';
remove client/scripts prefix

2024-02-07 19:17 UTC, jnaviask commented on packages/commonwealth/client/scripts/views/pages/new_proposal/compound_proposal_form.tsx
> +import { MixpanelGovernanceEvents } from '../../../../../shared/analytics/types';
use absolute import

2024-02-07 19:17 UTC, jnaviask commented on packages/commonwealth/client/scripts/views/pages/new_proposal/cosmos_proposal_form.tsx
> +import { useBrowserAnalyticsTrack } from 'client/scripts/hooks/useBrowserAnalyticsTrack';
see above

2024-02-07 19:17 UTC, jnaviask commented on packages/commonwealth/client/scripts/views/pages/new_proposal/cosmos_proposal_form.tsx
> +import { MixpanelGovernanceEvents } from '../../../../../shared/analytics/types';
see above

2024-02-07 19:17 UTC, jnaviask commented on packages/commonwealth/client/scripts/views/pages/new_proposal/sputnik_proposal_form.tsx
> +import { useBrowserAnalyticsTrack } from 'client/scripts/hooks/useBrowserAnalyticsTrack';
see above

2024-02-07 19:17 UTC, jnaviask commented on packages/commonwealth/client/scripts/views/pages/new_proposal/sputnik_proposal_form.tsx
> +import { MixpanelGovernanceEvents } from '../../../../../shared/analytics/types';
see above

2024-02-07 19:17 UTC, jnaviask commented on packages/commonwealth/client/scripts/views/pages/view_snapshot_proposal/snapshot_poll_card.tsx
> +import { useBrowserAnalyticsTrack } from 'client/scripts/hooks/useBrowserAnalyticsTrack';
see above

2024-02-07 19:17 UTC, jnaviask commented on packages/commonwealth/client/scripts/views/pages/view_snapshot_proposal/snapshot_poll_card.tsx
> +import { MixpanelSnapshotEvents } from '../../../../../shared/analytics/types';
see above

2024-02-08 03:01 UTC, Israellund commented on packages/commonwealth/client/scripts/views/components/ProposalCard/ProposalCard.tsx
> -  useEffect(() => {
@jnaviask There were duplicate useEffects.
https://github.com/hicommonwealth/commonwealth/blob/master/packages/commonwealth/client/scripts/views/components/ProposalCard/ProposalCard.tsx
<img width="1024" alt="Screenshot 2024-02-07 at 9 52 05 PM" src="https://github.com/hicommonwealth/commonwealth/assets/69872984/d74818c7-5780-4968-8c4b-9dbbe16f7967">

2024-02-08 18:43 UTC, Israellund commented
I commented out all checks and `governance.proposal()` call in `aave_proposal_form.tsx` to check that the event shows up on the Mixpanel dashboard. See video.

https://github.com/hicommonwealth/commonwealth/assets/69872984/0fc17266-495b-4478-9622-00d2ae10beb6

2024-02-13 21:04 UTC, CowMuon commented
Is this ready for review again? @Israellund (in any case, should go into 0.9.6 this week)

2024-02-13 21:09 UTC, Israellund commented
@CowMuon yes it should be good to review again

2024-02-21 13:30 UTC, Miaplacidus approved these changes
LGTM

2024-02-21 16:00 UTC, merged