Change stake modal to text input
hicommonwealth/commonwealth pull request #6807
Opened 2024-02-20 18:05 UTC by ianrowan

## Link to Issue
Closes: #6766 

## Description of Changes
- Converts stake amound from text to input
- updates style for text input
- adds dynamic character size for input

-bonus: includes an optimization for suggested gas in txs

## Test Plan
- Click buy stake, input amount via input
- test + and -
- attempt again on sell flow

## Other Considerations

- supports max characters of 8, this is far beyond any likely affordable eth amount

2024-02-20 19:06 UTC, mhagel approved these changes
tested. looks good

2024-02-21 13:00 UTC, masvelio requested changes
1. I bought one stake and I am getting 4e-8 ETH. Not sure if this issue is because of this PR or not, but it worked fine earlier.

![VOTE WEIGHT](https://github.com/hicommonwealth/commonwealth/assets/14819225/55d2fe7f-384c-44a3-a9dc-bfeaa1eb9479)

2. I am concerned about this idea in general as it has a lot of potential issues that are already visible, both on technical and visual sides. I would say it needs better thought and maybe input from design team. I am listing some pitfalls I run into
- I am able to delete value from the input and a. it becomes without value on blur and b. it gives me 2 console errors because fundamental rules of react inputs are violated

https://github.com/hicommonwealth/commonwealth/assets/14819225/80397a4a-3d3e-42f1-ad66-caed93dab27f

- I can type non numeric values 
![image](https://github.com/hicommonwealth/commonwealth/assets/14819225/73833c6d-da3e-41d9-89e2-1aaa4281afad)

- I can type very long numbers which breaks both design and functionality
![image](https://github.com/hicommonwealth/commonwealth/assets/14819225/dcece449-5c86-4ef4-b124-3ea5cdb4f02f)
![image](https://github.com/hicommonwealth/commonwealth/assets/14819225/d7aff69d-db0f-4a0a-8629-74008cb0dc68)
![image](https://github.com/hicommonwealth/commonwealth/assets/14819225/55e08aeb-f674-48ef-b8b6-7afeebf518dc)

- it looks bad on mobile in such cases (layout was not prepared for such a big numbers)
![image](https://github.com/hicommonwealth/commonwealth/assets/14819225/c85f71f7-ef3e-4abc-af61-1a9f63043fff)
![image](https://github.com/hicommonwealth/commonwealth/assets/14819225/952a2ea4-147e-4f06-b935-44a417a83cba)


In my opinion, it cannot get in with this shape. I think we should
- use number input
- add proper validation for max number values
- figure out better UI for mobile or/and big numbers

2024-02-21 16:51 UTC, ianrowan commented on packages/commonwealth/client/scripts/views/modals/ManageCommunityStakeModal/StakeExchangeForm/StakeExchangeForm.tsx
> +    : numberOfStakeToExchange > stakeBalance;
given that users can potentially input sell amounts larger than their holdings the user is show this message in sell now

2024-02-21 17:19 UTC, ianrowan commented on packages/commonwealth/client/scripts/views/modals/ManageCommunityStakeModal/StakeExchangeForm/StakeExchangeForm.tsx
> +import { CWTextInput } from 'client/scripts/views/components/component_kit/cw_text_input';
addressed

2024-02-21 17:19 UTC, ianrowan commented on packages/commonwealth/client/scripts/views/modals/ManageCommunityStakeModal/StakeExchangeForm/StakeExchangeForm.tsx
> +      : 'number';
addressed

2024-02-22 16:04 UTC, masvelio approved these changes
added some css tweaks in latest commit

2024-02-22 16:56 UTC, merged