Draft hex cosmos-evm
hicommonwealth/commonwealth pull request #6930
Opened 2024-02-27 23:49 UTC by mhagel

## Link to Issue
Closes: #6584 

## Description of Changes
- Adds FIXME widget to TODO page.
- 

## "How We Fixed It"

## Test Plan
- Unit tested the `FIXME()` call.
- CA (click around) tested on local and frack:
  - TODO page
  - 

## Deployment Plan

1. 

## Other Considerations

-

2024-03-12 22:42 UTC, timolegros requested changes
2 small changes otherwise LGTM!

2024-03-13 01:29 UTC, mhagel commented on packages/commonwealth/server/util/cosmosProxy.ts
> +      log.trace(
done

2024-03-13 15:50 UTC, mhagel commented on packages/commonwealth/client/scripts/controllers/app/webWallets/utils.ts
> +export const getCosmosEvmChains = (): string[] =>
good call. done

2024-03-13 17:37 UTC, timolegros commented on packages/commonwealth/server/util/cosmosProxy.ts
> +      log.trace(
@mhagel Can you update all the other logs as well? We shouldn't `JSON.stringify` anything into the error message anymore. Pino (our new logger) uses `fast-json-stringify` which is much faster than JSON.stringify. Any data that is passed to JSON.stringify should instead be passed as a context object.

2024-03-13 18:29 UTC, mhagel commented on packages/commonwealth/server/util/cosmosProxy.ts
> +      log.trace(
done @timolegros

2024-03-13 20:46 UTC, timolegros submitted a review, later dismissed

2024-04-12 13:31 UTC, timolegros commented
@CowMuon looks like Mark may have already solved some of our issues with EVM Cosmos in this PR. Massive shame we didn't merge this. @ianrowan let's get some reviews on this. I will resolve the conflicts today.

2024-04-19 14:29 UTC, Rotorsoft approved these changes
LGTM

2024-04-19 18:20 UTC, merged