Discord Bot Disconnect
hicommonwealth/commonwealth pull request #7144
Opened 2024-03-15 03:53 UTC by timolegros

## Link to Issue
Closes: #5853 

## Description of Changes
- Adds `/removeDiscordBotConfig` route
- Switch button from 'Reconnect' to 'Disconnect'
  - 'Reconnect' just retried the flow for connecting which actually throws an error and leaves the config in an inconsistent state. It also makes it impossible to switch which Discord server the Discord bot is connected to.

## Test Plan
- 

## Deployment Plan

1. 

## Other Considerations

-

2024-03-15 11:15 UTC, masvelio requested changes
move API call logic to react-query in `state/api`

2024-03-15 11:15 UTC, masvelio commented on packages/commonwealth/client/scripts/views/pages/CommunityManagement/Integrations/Discord/Discord.tsx
> +  const queryClient = useQueryClient();
Do not pollute component with this. See my other comment.

2024-03-15 11:15 UTC, masvelio commented on packages/commonwealth/client/scripts/views/pages/CommunityManagement/Integrations/Discord/Discord.tsx
> +  if (queryParams.has('discordConfigId')) {
fix the warnings

2024-03-15 11:15 UTC, masvelio commented on packages/commonwealth/client/scripts/views/pages/CommunityManagement/Integrations/Discord/Discord.tsx
> +      });
We can't do this anymore. We are in the process of tidy up the mess so please align with new pattern.
Basically API calls should by done with react-query and all of these api related logic should be handled in `state/api` directory, following existing patterns. As @mzparacha worked recently in this area, let's make sure that it is done properly

2024-03-18 11:30 UTC, mzparacha commented on packages/commonwealth/client/scripts/state/api/discord/removeDiscordBotConfig.ts
> +  await axios.post(`${app.serverUrl()}/removeDiscordBotConfig`, {
lets move `/removeDiscordBotConfig` as const to `/client/scripts/state/api/config.ts`

2024-03-18 11:31 UTC, mzparacha approved these changes

2024-03-18 16:10 UTC, merged