7023-pwaPromptAnimation
hicommonwealth/commonwealth pull request #7370
Opened 2024-04-04 15:54 UTC by lzach83

## Link to Issue
Closes: #7023 

## Description of Changes
- Using the `useAnimation` hook, added the animation to both `IOSPrompt` and `AndroidPrompt`

## Test Plan
- Run the website locally
- Ensure the animation occurs for both prompts

2024-04-08 15:57 UTC, Israellund approved these changes
LGTM, just have to fix the one code quality test

2024-04-09 09:42 UTC, masvelio commented
There is a moment when the modal backdrop is not fully aligned to the top bar which looks bad. Also, isn't animation too slow? Spec says 0.5s 

![image](https://github.com/hicommonwealth/commonwealth/assets/14819225/8dab7acd-a443-4d61-b31d-dd4cce03de94)


https://github.com/hicommonwealth/commonwealth/assets/14819225/90496c43-1bbe-4c1a-a3c7-d702485d54d2

2024-04-09 09:42 UTC, masvelio commented on packages/commonwealth/client/scripts/views/components/AddToHomeScreenPrompt/IOSPrompt/IOSPrompt.tsx
>    setShowPrompt,
remove all those warnings by removing unused props

2024-04-18 19:16 UTC, mzparacha approved these changes
Tested locally, LGTM. Please fix CI issues before merge.

2024-04-24 20:20 UTC, jnaviask requested changes
Getting the same "looks bad" as Marcin is, where the backdrop has space on the top during the animiation.

2024-04-26 15:13 UTC, burtonator approved these changes

2024-07-26 17:56 UTC, closed without merging