NewProposalMenu: Council Items
hicommonwealth/commonwealth pull request #747
Opened 2020-09-08 14:17 UTC by gdjohnson

Closes #685.

## Description

This branch adds the council Candidacy and CollectiveVote buttons to the NewProposalButton dropdown. A new "MenuStyle" switch has been added (in addition to ButtonStyle), and the NewProposalButton has been added to the Council page. The possibility of rendering the council buttons on all forum pages was explored, but ultimately abandoned, as there was significant unloaded chain data on discussions pages that prevented smooth modal rendering.

## How has this been tested?
NewProposalButton renders as it should; it is not possible to interact with it logged out, or without a connected address; in standard use cases of a logged-in account, the modals triggered as desired.

## Have proper tags been added (for bug, enhancement, breaking change)?
- [x] yes

## Does this PR affect any server routes?
- [ ] yes, and they are tested: [enter the % coverage here]
- [ ] yes, and they are not tested: [enter the % coverage here]
- [ ] yes, but I did not run tests
- [x] no

2020-09-08 21:24 UTC, raykyri requested changes
- There's a lot of duplicated code in the voting buttons. We don't need to change it now but just pointing this out
- No check for non-Substrate chains when looking up the council?

2020-09-09 14:26 UTC, gdjohnson commented
@raykyri isn't Council a Substrate-only feature?

2020-09-09 14:26 UTC, gdjohnson commented
Cleaned up the code redundancy; lmk re: above, otherwise should be good to go

2020-09-09 17:32 UTC, raykyri commented on server/routes/createComment.ts
> +  console.log(proposal);
^

2020-09-09 17:32 UTC, raykyri commented
> @raykyri isn't Council a Substrate-only feature?

Yeah but there's no check to make sure we are on a Substrate chain? At least I don't think I saw one

2020-09-10 00:54 UTC, raykyri commented
Need to QA more but I'll merge this now

2020-09-10 00:54 UTC, merged