implement symbol decimal lookup for erc20
hicommonwealth/commonwealth pull request #7654
Opened 2024-05-01 19:20 UTC by ianrowan

## Link to Issue
Closes: #7579 

## Description of Changes
- Implements stub to lookup contestToken and resolve decimals and symbol for ETH(automatically) and dynamic lookup for any ERC20

## Test Plan
- pass a contestAddress and ensure correct decimals and symbol of contestToken are returned

2024-05-02 18:29 UTC, timolegros requested changes

2024-05-03 19:43 UTC, rbennettcw approved these changes

2024-05-07 19:17 UTC, timolegros requested changes

2024-05-07 19:17 UTC, timolegros commented on libs/model/src/contest/Contests.projection.ts
> +  console.log('env', process.env.NODE_ENV);
```suggestion
```

2024-05-07 19:17 UTC, timolegros commented on libs/model/src/contest/Contests.projection.ts
> +          new Web3(community?.ChainNode?.url),
```suggestion
          new Web3(community?.ChainNode?.private_url || community?.ChainNode?.url),
```

2024-05-07 19:17 UTC, timolegros commented on libs/model/src/contest/Contests.projection.ts
> +    include: models.ChainNode,
```suggestion
    include: models.ChainNode.scope('withPrivateData'),
```

2024-05-08 14:39 UTC, ianrowan commented
CC @Rotorsoft do you know what's causing this build to fail after I merged master yesterday(related to projections in logs)?

2024-05-09 07:59 UTC, timolegros approved these changes

2024-05-09 14:35 UTC, merged