Graham.homepage activity
hicommonwealth/commonwealth pull request #780
Opened 2020-09-15 14:15 UTC by gdjohnson

Closes #731.

## Description
![image](https://user-images.githubusercontent.com/22281010/93217365-f5a8da80-f736-11ea-84fa-a513de44978f.png)

This branch displays, on a rolling basis, the past month's new thread count, as well as recent active users.

The /status endpoint now counts the number of threads created in the past 30 days in a given community, as well as collecting the list of all users (in AddressInfo format) who have created or updated a thread, comment, or reaction in the past 30 days. This data is stored in `app.recentActivity`. Both pieces of data are displayed on the homepage's CommunityCards, as pictured above—as a count for threads, and a UserGallery for members.

Homepage cards need some CSS to stay in gridded alignment, but it might be best to leave that to @raykyri.

## How has this been tested?

I've manually inspected the data to ensure proper fetching/sorting is occurring for each chain/community. I've tested different time boundaries to see how different levels of activity (e.g. many recently active users) would affect card rendering. 

## Have proper tags been added (for bug, enhancement, breaking change)?
- [x] yes

## Does this PR affect any server routes?
Currently, we don't have tests set up for the `/status` endpoint.

2020-09-15 18:39 UTC, raykyri requested changes
Made a few copy changes, only one comment at this point:

- Could we make it so that communities on the homepage are sorted in descending order by number of recently active threads? This will require moving some the monthlyThreads calculation around but it'll make a really big difference in making the page feel more active.

2020-09-16 15:31 UTC, gdjohnson commented on client/scripts/views/pages/home/community_cards.ts
> +import UserGallery from '../../components/widgets/user_gallery';
yeah sorry that's my auto-import actin up, lemme see if I can tweak settings

2020-09-16 16:56 UTC, gdjohnson commented
@raykyri Import cleaned up, and homepage sorting added

2020-09-16 19:11 UTC, raykyri approved these changes
LGTM

2020-09-16 19:11 UTC, merged