Refactor misc thread queries to new profile model
hicommonwealth/commonwealth pull request #8455
Opened 2024-07-12 17:32 UTC by Rotorsoft

## Link to Issue
Closes: #8454

## Description of Changes
- Replaces Profiles with User.profile
- Create temp response schema following old Profiles model - TO BE REMOVED later when UI gets migrated

## Test Plan
- Manually check thread and overview pages to load
- Pass unit tests

2024-07-16 19:41 UTC, timolegros requested changes
Searching profiles seems to be broken.

![image](https://github.com/user-attachments/assets/68d3c7d6-64f9-4494-97eb-230a6bbd4840)

2024-07-17 20:41 UTC, rbennettcw commented on packages/commonwealth/server/controllers/server_threads_methods/get_threads_by_id.ts
> +    console.log(t);
should remove log?

2024-07-17 20:42 UTC, rbennettcw approved these changes

2024-07-17 21:18 UTC, timolegros requested changes
![image](https://github.com/user-attachments/assets/c7360bbb-45c2-4e70-b9aa-2956122fb026)

Searching profiles works but clicking on a profile result breaks.

2024-07-17 21:32 UTC, Rotorsoft commented
Yes @timolegros this is an issue with the data. We have a lot of addresses with user_id and profile_id NULL

Can we solve this with a migration from Profiles to Addresses?

2024-07-17 21:47 UTC, timolegros commented
> Yes @timolegros this is an issue with the data. We have a lot of addresses with user_id and profile_id NULL
> 
> Can we solve this with a migration from Profiles to Addresses?

I don't think this is related to addresses that have `user_id` and/or `profile_id` null. The profile I clicked on is RhysFH which has profile id 13074. All of his addresses have a defined `profile_id`.

2024-07-17 21:48 UTC, timolegros commented
> Yes @timolegros this is an issue with the data. We have a lot of addresses with user_id and profile_id NULL
> 
> Can we solve this with a migration from Profiles to Addresses?



> > Yes @timolegros this is an issue with the data. We have a lot of addresses with user_id and profile_id NULL
> > Can we solve this with a migration from Profiles to Addresses?
> 
> I don't think this is related to addresses that have `user_id` and/or `profile_id` null. The profile I clicked on is RhysFH which has profile id 13074 and user id 2889. All of his addresses have a defined `profile_id`.

Additionally, I think addresses with null `user_id` and/or `profile_id` are addresses that started the sign-in process but didn't complete it. These should be excluded from search.

2024-07-18 00:47 UTC, Rotorsoft commented
> > Yes @timolegros this is an issue with the data. We have a lot of addresses with user_id and profile_id NULL
> > Can we solve this with a migration from Profiles to Addresses?
> 
> > > Yes @timolegros this is an issue with the data. We have a lot of addresses with user_id and profile_id NULL
> > > Can we solve this with a migration from Profiles to Addresses?
> > 
> > 
> > I don't think this is related to addresses that have `user_id` and/or `profile_id` null. The profile I clicked on is RhysFH which has profile id 13074 and user id 2889. All of his addresses have a defined `profile_id`.
> 
> Additionally, I think addresses with null `user_id` and/or `profile_id` are addresses that started the sign-in process but didn't complete it. These should be excluded from search.

I see. Fixed by filtering out any addresses where profile_id is null.

2024-07-18 13:37 UTC, timolegros approved these changes

2024-07-18 13:50 UTC, merged