Kaleem neslit.9501.merge all oveview
hicommonwealth/commonwealth pull request #9854
Opened 2024-11-07 16:20 UTC by KaleemNeslit

## Link to Issue
Closes: #9501 

## Description of Changes
- Added the Tabs in discussion page to show "All and Overview " page 
- keep the  functionality   for admins to set the default view of the community.

## "How We Fixed It"

- Added the Tabs in discussion page to show "All and Overview " page 
- keep the  functionality   for admins to set the default view of the community.
- 

## Test Plan
Goto and community and check the tabs to navigate btw all and overView page
-go community and then  in Admin Capabilities sidebar click the Community Profile and then scroll to Default page and then select the page type as default.
Here is the video of  test 

https://github.com/user-attachments/assets/240e16a7-9971-4e27-b943-fffed2653d80

2024-11-08 12:42 UTC, mzparacha commented on packages/commonwealth/client/scripts/views/pages/overview/index.tsx
this gets double padded in discussions page

<img width="1113" alt="image" src="https://github.com/user-attachments/assets/094253fb-baa9-4c8c-9590-78b5615a5ec3">

2024-11-08 12:44 UTC, mzparacha commented on packages/commonwealth/client/scripts/views/pages/overview/index.tsx
> +      params.set('tab', 'overview');
you'd have to update `HeaderWithFilters.tsx -> onFilterSelect()` logic for URL params setting to work correctly with this section. ex: `?featured=oldest or anything after '?'` should get removed when switching from 'all' to 'overview' tab.

2024-11-08 12:46 UTC, mzparacha commented on packages/commonwealth/client/scripts/views/pages/discussions/HeaderWithFilters/HeaderWithFilters.tsx
> +        )}
lets store the active tab in url as we do elsewhere. ex: visiting `/discussions?tab=all` should take user to all discussions and `/discussions?tab=overview` should take to overview + lets make sure the URL updates sync with the filters in discussion section

2024-11-08 12:48 UTC, mzparacha commented on packages/commonwealth/client/scripts/views/pages/discussions/HeaderWithFilters/HeaderWithFilters.tsx
filters are for the threads list api on the discussion section, lets remove them when active tab is overview as they won't work there.

2024-11-08 16:02 UTC, dillchen commented
Hey @KaleemNeslit sorry we updated the design -> Please see this file:

https://www.figma.com/design/dGPiswtnIfQIzSNOlB4MNC/Sticky-editor-%2B-Sidebar-%2B-Thread-UI?node-id=789-4056&t=0WhzNPyv8wyiMzgb-4

<img width="516" alt="image" src="https://github.com/user-attachments/assets/ee79c23c-aa93-492d-8941-e1b103893ed9">

2024-11-08 16:02 UTC, dillchen requested changes
please see previous comment

2024-11-08 16:15 UTC, KaleemNeslit commented
> please see previous comment

sure i am looking into it

2024-11-08 16:23 UTC, KaleemNeslit commented
@dillchen Sorry I didn't get the requirements here, Is it this change of [design](https://github.com/hicommonwealth/commonwealth/issues/9502) you are talking about ?
If it's then i'm already assigned this task and will work on it, If no then can you please elaborate on it what changes are required for UI?

2024-11-08 19:10 UTC, dillchen commented
For visibility, we're gonna use these for icons for All / Overview: https://www.figma.com/design/dGPiswtnIfQIzSNOlB4MNC/Sticky-editor-%2B-Sidebar-%2B-Thread-UI?node-id=849-2150&t=0WhzNPyv8wyiMzgb-4

2024-11-11 15:13 UTC, KaleemNeslit commented
![image](https://github.com/user-attachments/assets/37ec6ea2-bf09-4fb6-95a5-7c2e05ee9137)
@masvelio @mzparacha  @Israellund  i made changes according to new design . I change the tabs with select

2024-11-12 17:00 UTC, dillchen approved these changes

2024-11-13 12:04 UTC, mzparacha commented on packages/commonwealth/client/scripts/views/pages/overview/index.tsx
> +  console.log('i am called');
please remove this

2024-11-13 12:05 UTC, mzparacha approved these changes
The all/overview dropdown gets removed when any filter is selected in the all tab
<img width="1700" alt="image" src="https://github.com/user-attachments/assets/607cf8c3-5b76-4f30-8025-1c03a6ed3449">

Other than this, lgtm so approving in advance.

2024-11-13 16:55 UTC, KaleemNeslit commented
@mzparacha fixed mentioned comments also showed All/Overview filter on all other sorts filters as well.
@Israellund Kindly review it again Fixed mentioned refactors.

2024-11-13 17:37 UTC, Israellund commented
@KaleemNeslit This looks good, feel free to merge today. thanks

2024-11-13 18:28 UTC, merged